@php
      // Generate simple math CAPTCHA
      $num1 = rand(1, 10);
      $num2 = rand(1, 10);
      $captcha_question = "$num1 + $num2";
      $captcha_answer = $num1 + $num2;
@endphp
@extends('layouts.guest1')
@section('title', __('auth.register.title'))
@section('content')

<!-- Fintech Trading Platform Registration -->
<div class="min-h-screen bg-gray-900 relative overflow-hidden py-8 sm:py-12">
    <div class="relative z-10 flex items-center justify-center px-4 sm:px-6 lg:px-8">
        <div class="w-full max-w-2xl">
            <!-- Professional Trading Registration Card -->
            <div class="bg-gray-900 border border-gray-700 rounded-2xl sm:rounded-3xl p-6 sm:p-8 lg:p-10 shadow-2xl"
                 id="kayitFormu">

                <!-- Header Section -->
                <div class="text-center mb-8">
                    <!-- Logo -->
                    <div class="flex items-center justify-center mb-6">
                        <img src="{{ asset('storage/'.$settings->logo)}}"
                             class="h-12 sm:h-16 w-auto"
                             alt="{{ $settings->site_name }}" />
                    </div>

                    <!-- Title -->
                    <h1 class="text-2xl sm:text-3xl lg:text-4xl font-bold text-white mb-2">
                        {{ __('auth.register.join_platform', ['site_name' => $settings->site_name]) }}
                    </h1>
                    <p class="text-gray-300 text-sm sm:text-base lg:text-lg mb-6">
                        {{ __('auth.register.start_trading_journey') }}
                    </p>

                    <!-- Trading Stats - Mobile Responsive -->
                    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-6 text-xs sm:text-sm">
                        <!--<div class="text-center p-3 bg-gray-800/50 rounded-xl border border-gray-700/50">-->
                        <!--    <div class="flex items-center justify-center gap-1 text-green-400 mb-1">-->
                        <!--        <div class="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>-->
                        <!--        <span class="font-semibold">99.9% Uptime</span>-->
                        <!--    </div>-->
                        <!--    <div class="text-gray-400">Reliable Platform</div>-->
                        <!--</div>-->
                        <!--<div class="text-center p-3 bg-gray-800/50 rounded-xl border border-gray-700/50">-->
                        <!--    <div class="flex items-center justify-center gap-1 text-blue-400 mb-1">-->
                        <!--        <x-heroicon name="shield-check" class="w-3 h-3" />-->
                        <!--        <span class="font-semibold">Bank-Grade</span>-->
                        <!--    </div>-->
                        <!--    <div class="text-gray-400">Security</div>-->
                        <!--</div>-->
                        <div class="text-center p-3 bg-gray-800/50 rounded-xl border border-gray-700/50">
                            <div class="flex items-center justify-center gap-1 text-cyan-400 mb-1">
                                <x-heroicon name="users" class="w-3 h-3" />
                                <span class="font-semibold">{{ __('auth.register.investor_count') }}</span>
                            </div>
                            <div class="text-gray-400">{{ __('auth.register.community') }}</div>
                        </div>
                    </div>
                </div>

                <!-- Enhanced Progress Steps - Mobile Optimized -->
                <div class="mb-8">
                    <div class="flex items-center justify-between sm:justify-center sm:space-x-8" id="steps-container">
                        <!-- Steps will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Error Summary Section -->
                @if ($errors->any())
                    <div class="mb-6 p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
                        <div class="flex items-start gap-3">
                            <div class="p-1 bg-red-500/20 rounded-lg mt-0.5">
                                <x-heroicon name="exclamation-triangle" class="w-5 h-5 text-red-400" />
                            </div>
                            <div class="flex-1">
                                <h4 class="text-lg font-bold text-red-300 mb-2">{{ __('auth.register.please_fix_issues') }}</h4>
                                <ul class="space-y-1">
                                    @foreach ($errors->all() as $error)
                                        <li class="text-sm text-red-200 flex items-start gap-2">
                                            <x-heroicon name="x-circle" class="w-4 h-4 text-red-400 mt-0.5 flex-shrink-0" />
                                            <span>{{ $error }}</span>
                                        </li>
                                    @endforeach
                                </ul>
                                <div class="mt-3 text-xs text-red-300/80">
                                    <x-heroicon name="information-circle" class="w-3 h-3 inline mr-1" />
                                    {{ __('auth.register.scroll_fix_fields') }}
                                </div>
                            </div>
                        </div>
                    </div>
                @endif

                <!-- Registration Form -->
                <form action="{{ route('register') }}" method="POST" class="space-y-6" id="register">
                    @csrf

                    <!-- Step 1: Personal Information -->
                    <div id="step-0" class="form-step">

                        <!-- Step Header -->
                        <div class="mb-6 p-4 bg-blue-500/10 rounded-xl border border-blue-500/20">
                            <div class="flex items-center gap-3">
                                <div class="p-2 bg-blue-500/20 rounded-lg">
                                    <x-heroicon name="user-circle" class="w-5 h-5 text-blue-400" />
                                </div>
                                <div>
                                    <h3 class="text-lg sm:text-xl font-bold text-white">{{ __('auth.register.personal_info') }}</h3>
                                    <p class="text-gray-400 text-sm">{{ __('auth.register.create_trading_profile') }}</p>
                                </div>
                            </div>
                        </div>

                        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
                            <!-- Username Field -->
                            <div class="space-y-2">
                                <label for="username" class="block text-sm font-bold text-gray-200">
                                    {{ __('auth.forms.trading_username') }} <span class="text-red-400">*</span>
                                </label>
                                <div class="relative group">
                                    <div class="absolute inset-y-0 left-0 flex items-center pl-4">
                                        <x-heroicon name="user" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                    </div>
                                    <input type="text" name="username" id="username" required
                                           class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-4 py-4 text-white placeholder-gray-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold"
                                           placeholder="{{ __('auth.forms.choose_username') }}">
                                </div>
                                @error('username')
                                    <p class="text-sm text-red-400 flex items-center gap-1">
                                        <x-heroicon name="exclamation-circle" class="w-4 h-4" />{{ $message }}
                                    </p>
                                @enderror
                            </div>

                            <!-- Full Name Field -->
                            <div class="space-y-2">
                                <label for="name" class="block text-sm font-bold text-gray-200">
                                    {{ __('auth.forms.full_name') }} <span class="text-red-400">*</span>
                                </label>
                                <div class="relative group">
                                    <div class="absolute inset-y-0 left-0 flex items-center pl-4">
                                        <x-heroicon name="user-check" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                    </div>
                                    <input type="text" name="name" id="name" required
                                           class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-4 py-4 text-white placeholder-gray-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold"
                                           placeholder="{{ __('auth.forms.enter_full_name') }}">
                                </div>
                                @error('name')
                                    <p class="text-sm text-red-400 flex items-center gap-1">
                                        <x-heroicon name="exclamation-circle" class="w-4 h-4" />{{ $message }}
                                    </p>
                                @enderror
                            </div>

                            <!-- Email Field -->
                            <div class="space-y-2">
                                <label for="email" class="block text-sm font-bold text-gray-200">
                                    {{ __('auth.forms.email_address') }} <span class="text-red-400">*</span>
                                </label>
                                <div class="relative group">
                                    <div class="absolute inset-y-0 left-0 flex items-center pl-4">
                                        <x-heroicon name="envelope" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                    </div>
                                    <input type="email" name="email" id="email" required
                                           class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-4 py-4 text-white placeholder-gray-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold"
                                           placeholder="{{ __('auth.forms.email_example') }}">
                                </div>
                                @error('email')
                                    <p class="text-sm text-red-400 flex items-center gap-1">
                                        <x-heroicon name="exclamation-circle" class="w-4 h-4" />{{ $message }}
                                    </p>
                                @enderror
                            </div>

                            <!-- Phone Field -->
                            <div class="space-y-2">
                                <label for="phone" class="block text-sm font-bold text-gray-200">
                                    {{ __('auth.forms.phone_number') }} <span class="text-red-400">*</span>
                                </label>
                                <div class="relative group">
                                    <div class="absolute inset-y-0 left-0 flex items-center pl-4">
                                        <x-heroicon name="phone" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                    </div>
                                    <input type="tel" name="phone" id="phone" required
                                           class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-4 py-4 text-white placeholder-gray-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold"
                                           placeholder="{{ __('auth.forms.phone_example') }}">
                                </div>
                            </div>
                        </div>
                    </div>

                <!-- Step 2: Location & Currency -->
                <div id="step-1" class="form-step" style="display: none;">

                    <!-- Step Header -->
                    <div class="mb-6 p-4 bg-purple-500/10 rounded-xl border border-purple-500/20">
                        <div class="flex items-center gap-3">
                            <div class="p-2 bg-purple-500/20 rounded-lg">
                                <x-heroicon name="globe-2" class="w-5 h-5 text-purple-400" />
                            </div>
                            <div>
                                <h3 class="text-lg sm:text-xl font-bold text-white">{{ __('auth.register.location') }}</h3>
                                <p class="text-gray-400 text-sm">{{ __('auth.register.regional_trading_preferences') }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="grid grid-cols-1 sm:grid-cols-1 gap-4 sm:gap-6">
                        <!-- Country Field -->
                        <div class="space-y-2">
                            <label for="country" class="block text-sm font-bold text-gray-200">
                                {{ __('auth.forms.country') }} <span class="text-red-400">*</span>
                            </label>
                            <div class="relative group">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-4 z-10">
                                    <x-heroicon name="flag" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                </div>
                                <select name="country" id="country" required
                                        class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-8 py-4 text-white focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold appearance-none">
                                    <option selected disabled class="text-gray-400">{{ __('auth.forms.select_country') }}</option>
                                    @include('auth.countries')
                                </select>
                                <div class="absolute inset-y-0 right-0 flex items-center pr-4 pointer-events-none">
                                    <x-heroicon name="chevron-down" class="h-4 w-4 text-gray-400" />
                                </div>
                            </div>
                        </div>

                        <!-- Currency Field -->
                        {{-- <div class="space-y-2">
                            <label for="select_c" class="block text-sm font-bold text-gray-200">
                                Preferred Currency <span class="text-red-400">*</span>
                            </label>
                            <div class="relative group">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-4 z-10">
                                    <x-heroicon name="banknote" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                </div>
                                <input name="s_currency" value="{{ $settings->s_currency }}" id="s_c" type="hidden">
                                <select name="currency" id="select_c" onchange="changecurr()" required
                                        class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-8 py-4 text-white focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold appearance-none">
                                    <option selected disabled class="text-gray-400">Select trading currency</option>
                                    @foreach ($currencies as $key => $currency)
                                        <option id="{{ $key }}" value="<?php echo html_entity_decode($currency); ?>" class="text-white bg-gray-900">
                                            {{ $key . ' (' . html_entity_decode($currency) . ')' }}</option>
                                    @endforeach
                                </select>
                                <div class="absolute inset-y-0 right-0 flex items-center pr-4 pointer-events-none">
                                    <x-heroicon name="chevron-down" class="h-4 w-4 text-gray-400" />
                                </div>
                            </div>
                        </div> --}}
                    </div>

                    <!-- Trading Preferences Info -->
                    <div class="mt-6 p-4 bg-blue-500/10 rounded-xl border border-blue-500/20">
                        <div class="flex items-start gap-3">
                            <x-heroicon name="information-circle" class="w-5 h-5 text-blue-400 mt-0.5 flex-shrink-0" />
                            <div class="text-sm">
                                <p class="text-blue-300 font-bold mb-1">{{ __('auth.register.regional_trading_info') }}</p>
                                <p class="text-gray-300">{{ __('auth.register.location_benefits') }}</p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Step 3: Security -->
                <div id="step-2" class="form-step" style="display: none;">

                    <!-- Step Header -->
                    <div class="mb-6 p-4 bg-green-500/10 rounded-xl border border-green-500/20">
                        <div class="flex items-center gap-3">
                            <div class="p-2 bg-green-500/20 rounded-lg">
                                <x-heroicon name="shield-check" class="w-5 h-5 text-green-400" />
                            </div>
                            <div>
                                <h3 class="text-lg sm:text-xl font-bold text-white">{{ __('auth.register.account_security') }}</h3>
                                <p class="text-gray-400 text-sm">{{ __('auth.register.secure_trading_account') }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
                        <!-- Password Field -->
                        <div class="space-y-2">
                            <label for="password" class="block text-sm font-bold text-gray-200">
                                {{ __('auth.forms.password') }} <span class="text-red-400">*</span>
                            </label>
                            <div class="relative group">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-4">
                                    <x-heroicon name="lock-closed" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                </div>
                                <input type="password" name="password" id="password" required
                                       autocomplete="new-password"
                                       class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-4 py-4 text-white placeholder-gray-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold"
                                       placeholder="{{ __('auth.forms.create_strong_password') }}">
                            </div>
                            @error('password')
                                <p class="text-sm text-red-400 flex items-center gap-1">
                                    <x-heroicon name="exclamation-circle" class="w-4 h-4" />{{ $message }}
                                </p>
                            @enderror
                        </div>

                        <!-- Confirm Password Field -->
                        <div class="space-y-2">
                            <label for="password_confirmation" class="block text-sm font-bold text-gray-200">
                                {{ __('auth.forms.confirm_password') }} <span class="text-red-400">*</span>
                            </label>
                            <div class="relative group">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-4">
                                    <x-heroicon name="key" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                </div>
                                <input type="password" name="password_confirmation" id="password_confirmation" required
                                       autocomplete="new-password"
                                       class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-4 py-4 text-white placeholder-gray-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold"
                                       placeholder="{{ __('auth.forms.confirm_password_placeholder') }}">
                            </div>
                        </div>
                    </div>

                    <!-- CAPTCHA Section -->
                    <div class="space-y-4 mt-6">
                        <div class="space-y-2">
                            <label for="captcha" class="block text-sm font-bold text-gray-200">
                                {{ __('auth.register.math_verification') }} <span class="text-red-400">*</span>
                            </label>

                            <!-- CAPTCHA Display -->
                            <div class="bg-gray-800 border border-gray-600 rounded-xl p-4 mb-3">
                                <div class="flex items-center justify-center">
                                    <div class="bg-gradient-to-r from-blue-900 to-purple-900 rounded-lg p-4 border border-gray-600">
                                        <div class="text-center">
                                            <p class="text-sm text-gray-300 mb-3 font-medium">{{ __('auth.register.math_question') }}</p>
                                            <div class="bg-gray-900 rounded-lg px-8 py-4 border border-gray-700">
                                                <span class="text-3xl font-bold text-green-400 tracking-wide select-none"
                                                      style="font-family: 'Arial', sans-serif;">
                                                    {{ $captcha_question }} = ?
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- CAPTCHA Input -->
                            <div class="relative group">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-4">
                                    <x-heroicon name="calculator" class="h-5 w-5 text-gray-400 group-focus-within:text-blue-400 transition-colors" />
                                </div>
                                <input type="number" name="captcha" id="captcha" required
                                       class="block w-full rounded-xl border border-gray-600 bg-gray-900 pl-12 pr-4 py-4 text-white placeholder-gray-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-400/20 focus:bg-gray-800 transition-all duration-200 text-sm font-bold text-center"
                                       placeholder="{{ __('auth.register.math_answer_placeholder') }}"
                                       autocomplete="off"
                                       min="0"
                                       max="99">
                            </div>

                            @error('captcha')
                                <p class="text-sm text-red-400 flex items-center gap-1">
                                    <x-heroicon name="exclamation-circle" class="w-4 h-4" />{{ $message }}
                                </p>
                            @enderror

                            <!-- Helper text -->
                            <p class="text-xs text-gray-400 flex items-center gap-1">
                                <x-heroicon name="information-circle" class="w-3 h-3" />
                                {{ __('auth.register.math_helper_text') }}
                            </p>
                        </div>
                    </div>

                    <!-- Hidden CAPTCHA confirmation -->
                    <input type="hidden" name="captcha_confirmation" value="{{ $captcha_answer }}">

                    @if (Session::has('ref_by'))
                        <input type="hidden" name="ref_by" value="{{ session('ref_by') }}" required>
                    @endif

                    <!-- Password Requirements -->
                    <div class="mt-6 p-4 bg-gray-800/50 rounded-xl border border-gray-700">
                        <p class="text-sm font-bold text-gray-200 mb-2">{{ __('auth.register.password_requirements') }}</p>
                        <ul class="text-xs text-gray-300 space-y-1">
                            <li class="flex items-center gap-2">
                                <x-heroicon name="check" class="w-3 h-3 text-green-400" />
                                {{ __('auth.register.password_min_length') }}
                            </li>
                            <li class="flex items-center gap-2">
                                <x-heroicon name="check" class="w-3 h-3 text-green-400" />
                                {{ __('auth.register.password_mixed_case') }}
                            </li>
                            <li class="flex items-center gap-2">
                                <x-heroicon name="check" class="w-3 h-3 text-green-400" />
                                {{ __('auth.register.password_special_char') }}
                            </li>
                        </ul>
                    </div>

                    <!-- Terms Agreement -->
                    <div class="mt-6 p-6 bg-blue-500/10 rounded-xl border border-blue-500/20">
                        <div class="flex items-start gap-4">
                            <div class="flex items-center h-5 mt-1">
                                <input type="checkbox" name="agree" id="agree" required
                                       class="h-4 w-4 rounded border-gray-600 bg-gray-900 text-blue-500 focus:ring-2 focus:ring-blue-400/20 transition-colors">
                            </div>
                            <div class="flex-1">
                                <label for="agree" class="text-sm font-bold text-gray-200 leading-relaxed">
                                    {{ __('auth.register.terms_accept_start', ['site_name' => $settings->site_name]) }}
                                    <a href="rules" target="_blank" class="text-blue-400 hover:text-blue-300 font-bold underline underline-offset-2">
                                        {{ __('auth.register.terms_conditions') }}
                                    </a>
                                    {{ __('auth.register.terms_accept_and') }}
                                    <a href="#" target="_blank" class="text-blue-400 hover:text-blue-300 font-bold underline underline-offset-2">
                                        {{ __('auth.register.privacy_policy') }}
                                    </a>
                                    {{ __('auth.register.terms_accept_end') }}
                                </label>
                                <p class="text-xs text-gray-400 mt-2">
                                    {{ __('auth.register.age_market_consent') }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Enhanced Navigation Buttons -->
                <div class="flex flex-col sm:flex-row justify-between items-center mt-10 pt-8 border-t border-gray-700 gap-4" id="navigation-buttons">
                    <!-- Previous Button -->
                    <button type="button" id="prev-btn" onclick="oncekiAdim()"
                            style="display: none;"
                            class="inline-flex items-center gap-2 px-6 py-3 text-gray-400 hover:text-white transition-all duration-200 rounded-xl hover:bg-gray-800/50 group">
                        <x-heroicon name="arrow-left" class="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                        <span class="font-bold">{{ __('auth.register.previous_step') }}</span>
                    </button>

                    <!-- Progress Indicator -->
                    <div class="flex items-center gap-2 text-sm text-gray-400">
                        <span id="step-indicator" class="font-bold">{{ __('auth.register.step_indicator', ['current' => '1', 'total' => '3']) }}</span>
                    </div>

                    <!-- Next Button -->
                    <button type="button" id="next-btn" onclick="sonrakiAdim()"
                            class="inline-flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-bold rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 group">
                        <span>{{ __('auth.register.continue') }}</span>
                        <x-heroicon name="arrow-right" class="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </button>

                    <!-- Create Account Button -->
                    <button type="submit" id="submit-btn"
                            style="display: none;"
                            class="inline-flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white font-bold rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 group">
                        <x-heroicon name="user-plus" class="w-5 h-5" />
                        <span>{{ __('auth.register.create_trading_account') }}</span>
                        <x-heroicon name="sparkles" class="w-4 h-4 group-hover:rotate-12 transition-transform" />
                    </button>
                </div>

                <!-- Professional Footer -->
                <div class="mt-8 text-center space-y-4">
                    <div class="flex items-center justify-center gap-6 text-sm">
                        <p class="text-gray-400">
                            {{ __('auth.register.already_have_account') }}
                            <a href="{{ route('login') }}"
                               class="font-bold text-blue-400 hover:text-blue-300 transition-colors underline underline-offset-2">
                                {{ __('auth.register.login_here') }}
                            </a>
                        </p>
                    </div>

                    <!-- Trust Indicators -->
                    <div class="flex items-center justify-center gap-8 py-4 text-xs text-gray-500">
                        <div class="flex items-center gap-1">
                            <x-heroicon name="shield-check" class="w-3 h-3" />
                            <span>{{ __('auth.register.ssl_security') }}</span>
                        </div>
                        <div class="flex items-center gap-1">
                            <x-heroicon name="lock-closed" class="w-3 h-3" />
                            <span>{{ __('auth.register.encryption_256bit') }}</span>
                        </div>
                        <div class="flex items-center gap-1">
                            <x-heroicon name="award" class="w-3 h-3" />
                            <span>{{ __('auth.register.regulated_platform') }}</span>
                        </div>
                    </div>

                    <p class="text-xs text-gray-500">
                        {{ __('auth.register.copyright', ['year' => date('Y'), 'site_name' => $settings->site_name]) }} |
                        {{ __('auth.register.licensed_platform') }}
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

    <style>
        .form-step {
            opacity: 1;
            transform: translateX(0);
            transition: opacity 0.3s ease-out, transform 0.3s ease-out;
        }
        
        .form-step.hiding {
            opacity: 0;
            transform: translateX(-20px);
        }
        
        .form-step.showing {
            opacity: 1;
            transform: translateX(0);
        }
    </style>

    <script>
        // Vanilla JavaScript Multi-Step Form
        let currentStep = 0;
        const steps = [
            { title: '{{ __('auth.register.personal_info') }}', description: '{{ __('auth.register.basic_info') }}', completed: false },
            { title: '{{ __('auth.register.location') }}', description: '{{ __('auth.register.regional_settings') }}', completed: false },
            { title: '{{ __('auth.register.security') }}', description: '{{ __('auth.register.account_protection') }}', completed: false }
        ];

        function updateStepsDisplay() {
            const stepsContainer = document.getElementById('steps-container');
            stepsContainer.innerHTML = '';

            steps.forEach((step, index) => {
                const stepDiv = document.createElement('div');
                stepDiv.className = 'flex flex-col items-center';
                
                const circleClass = currentStep > index ? 'bg-green-500 text-white' :
                                  currentStep === index ? 'bg-blue-500 text-white' :
                                  'bg-gray-700 text-gray-400';
                
                const labelClass = currentStep >= index ? 'text-white' : 'text-gray-500';
                const lineClass = currentStep > index ? 'bg-green-500' : 'bg-gray-700';
                
                stepDiv.innerHTML = `
                    <div class="relative mb-2">
                        <div class="flex items-center justify-center w-8 h-8 sm:w-10 sm:h-10 rounded-full text-xs sm:text-sm font-bold transition-all duration-300 ${circleClass}">
                            ${currentStep > index ? '<svg class="w-4 h-4 sm:w-5 sm:h-5" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>' : (index + 1)}
                        </div>
                        ${currentStep === index ? '<div class="absolute inset-0 w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-blue-500 animate-ping opacity-20"></div>' : ''}
                    </div>
                    <div class="text-center">
                        <div class="text-xs sm:text-sm font-medium transition-colors duration-300 ${labelClass}">${step.title}</div>
                        <div class="text-xs text-gray-500 hidden sm:block">${step.description}</div>
                    </div>
                    ${index < steps.length - 1 ? `<div class="hidden sm:block absolute top-4 left-1/2 w-16 h-0.5 transition-colors duration-300 ${lineClass}" style="transform: translateX(2rem);"></div>` : ''}
                `;
                
                stepsContainer.appendChild(stepDiv);
            });

        }

        function updateNavigation() {
            const prevBtn = document.getElementById('prev-btn');
            const nextBtn = document.getElementById('next-btn');
            const submitBtn = document.getElementById('submit-btn');
            const indicator = document.getElementById('step-indicator');

            prevBtn.style.display = currentStep > 0 ? 'inline-flex' : 'none';
            nextBtn.style.display = currentStep < steps.length - 1 ? 'inline-flex' : 'none';
            submitBtn.style.display = currentStep === steps.length - 1 ? 'inline-flex' : 'none';
            indicator.textContent = `{{ __('auth.register.step') }} ${currentStep + 1} / ${steps.length}`;
        }

        function showStep(stepIndex) {
            // Hide all steps
            document.querySelectorAll('.form-step').forEach((step, index) => {
                if (index === stepIndex) {
                    step.style.display = 'block';
                    step.classList.add('showing');
                    step.classList.remove('hiding');
                } else {
                    step.style.display = 'none';
                    step.classList.remove('showing');
                    step.classList.add('hiding');
                }
            });
            
            updateStepsDisplay();
            updateNavigation();
            window.scrollTo({ top: 0, behavior: 'smooth' });
        }

        function sonrakiAdim() {
            if (validateCurrentStep()) {
                steps[currentStep].completed = true;
                if (currentStep < steps.length - 1) {
                    currentStep++;
                    showStep(currentStep);
                }
            }
        }

        function oncekiAdim() {
            if (currentStep > 0) {
                currentStep--;
                showStep(currentStep);
            }
        }

        function validateCurrentStep() {
            let isValid = true;
            let missingFields = [];

            if (currentStep === 0) {
                const fields = [
                    { id: 'username', name: '{{ __('auth.forms.username') }}' },
                    { id: 'name', name: '{{ __('auth.forms.full_name') }}' },
                    { id: 'email', name: '{{ __('auth.forms.email_address') }}' },
                    { id: 'phone', name: '{{ __('auth.forms.phone_number') }}' }
                ];

                fields.forEach(field => {
                    const element = document.getElementById(field.id);
                    const value = element.value.trim();
                    if (!value) {
                        missingFields.push(field.name);
                        isValid = false;
                        element.classList.add('border-red-500', 'bg-red-900/20');
                        element.classList.remove('border-gray-600');
                    } else {
                        element.classList.remove('border-red-500', 'bg-red-900/20');
                        element.classList.add('border-gray-600');
                    }
                });

                const emailElement = document.getElementById('email');
                const email = emailElement.value.trim();
                if (email && !email.includes('@')) {
                    missingFields.push('{{ __('auth.validation.valid_email_format') }}');
                    isValid = false;
                    emailElement.classList.add('border-red-500', 'bg-red-900/20');
                }
            } else if (currentStep === 1) {
                const countryElement = document.getElementById('country');
                if (!countryElement.value) {
                    missingFields.push('{{ __('auth.forms.country') }}');
                    isValid = false;
                    countryElement.classList.add('border-red-500', 'bg-red-900/20');
                } else {
                    countryElement.classList.remove('border-red-500', 'bg-red-900/20');
                }
            } else if (currentStep === 2) {
                const passwordElement = document.getElementById('password');
                const confirmPasswordElement = document.getElementById('password_confirmation');
                const captchaElement = document.getElementById('captcha');
                const agreeElement = document.getElementById('agree');

                const password = passwordElement.value;
                const confirmPassword = confirmPasswordElement.value;
                const captcha = captchaElement.value.trim();
                const agree = agreeElement.checked;

                if (!password) {
                    missingFields.push('{{ __('auth.forms.password') }}');
                    isValid = false;
                    passwordElement.classList.add('border-red-500', 'bg-red-900/20');
                } else if (password.length < 8) {
                    missingFields.push('{{ __('auth.validation.password_min_8_chars') }}');
                    isValid = false;
                    passwordElement.classList.add('border-red-500', 'bg-red-900/20');
                } else {
                    passwordElement.classList.remove('border-red-500', 'bg-red-900/20');
                }

                if (!confirmPassword || password !== confirmPassword) {
                    missingFields.push('{{ __('auth.forms.confirm_password') }}');
                    isValid = false;
                    confirmPasswordElement.classList.add('border-red-500', 'bg-red-900/20');
                } else {
                    confirmPasswordElement.classList.remove('border-red-500', 'bg-red-900/20');
                }

                if (!captcha) {
                    missingFields.push('{{ __('auth.register.math_verification') }}');
                    isValid = false;
                    captchaElement.classList.add('border-red-500', 'bg-red-900/20');
                } else {
                    captchaElement.classList.remove('border-red-500', 'bg-red-900/20');
                }

                if (!agree) {
                    missingFields.push('{{ __('auth.register.terms_acceptance') }}');
                    isValid = false;
                }
            }

            if (!isValid) {
                const message = missingFields.length === 1
                    ? `{{ __('auth.validation.please_provide') }}: ${missingFields[0]}`
                    : `{{ __('auth.validation.please_fill_fields') }}: ${missingFields.join(', ')}`;
                alert(`{{ __('auth.validation.required_fields') }}: ${message}`);
            }

            return isValid;
        }

        // Initialize form when page loads
        document.addEventListener('DOMContentLoaded', function() {
            showStep(0);
            
            // Form submission enhancement
            const form = document.getElementById('register');
            if (form) {
                form.addEventListener('submit', function(e) {
                    const submitBtn = form.querySelector('button[type="submit"]');
                    if (submitBtn) {
                        submitBtn.disabled = true;
                        submitBtn.innerHTML = '<svg class="w-4 h-4 animate-spin mr-2" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>{{ __('auth.register.creating_account') }}';
                    }
                });
            }

            // Auto-scroll to errors if they exist
            const errorSummary = document.querySelector('.bg-red-500\\/10');
            if (errorSummary) {
                setTimeout(() => {
                    errorSummary.scrollIntoView({ behavior: 'smooth', block: 'center' });
                    errorSummary.style.animation = 'shake 0.5s ease-in-out';
                }, 100);
            }

        });
    </script>

    <style>
        @keyframes shake {
            0%, 100% { transform: translateX(0); }
            25% { transform: translateX(-5px); }
            75% { transform: translateX(5px); }
        }
    </style>
@endsection

