<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Phrase;
use App\Models\PhraseTranslation;

class AdditionalUserManagementPhrasesSeeder extends Seeder
{
    public function run()
    {
        $phrases = [
            // Profile & Security
            'admin.profile.change_password' => 'Şifre Değiştir',
            'admin.profile.strong_password_message' => 'Hesap güvenliğiniz için güçlü bir şifre belirleyin',
            'admin.profile.password_security' => 'Şifre Güvenliği',
            'admin.profile.current_password_placeholder' => 'Mevcut şifrenizi girin',
            'admin.profile.new_password_placeholder' => 'Yeni şifrenizi girin',
            'admin.profile.password_strength' => 'Şifre Gücü',
            'admin.profile.confirm_password_placeholder' => 'Yeni şifrenizi tekrar girin',
            'admin.profile.clear' => 'Temizle',
            'admin.profile.update_password' => 'Şifreyi Güncelle',
            'admin.profile.password_requirements' => 'Güvenli Şifre Gereksinimleri',
            'admin.profile.min_8_chars' => 'En az 8 karakter',
            'admin.profile.uppercase' => 'Büyük harf (A-Z)',
            'admin.profile.lowercase' => 'Küçük harf (a-z)',
            'admin.profile.numbers' => 'Rakam (0-9)',
            'admin.profile.special_chars' => 'Özel karakter (!@#$%)',
            'admin.profile.passwords_match' => 'Şifreler eşleşmeli',
            'admin.profile.updating' => 'Güncelleniyor...',
            'admin.profile.account_profile' => 'Hesap Profil Bilgileri',
            'admin.profile.manage_personal_info' => 'Kişisel bilgilerinizi ve güvenlik ayarlarınızı yönetin',
            'admin.profile.profile_info' => 'Profil Bilgileri',
            'admin.profile.enter_name' => 'Adınızı girin',
            'admin.profile.enter_surname' => 'Soyadınızı girin',
            'admin.profile.enable' => 'Etkinleştir',
            'admin.profile.disable' => 'Devre Dışı Bırak',
            'admin.profile.reset' => 'Sıfırla',
            'admin.profile.update' => 'Güncelle',
            'admin.profile.security_info' => 'Güvenlik Bilgisi',
            'admin.profile.keep_updated' => 'Profil bilgilerinizi güncel tutun',
            'admin.profile.enable_2fa' => 'Güvenliğiniz için iki faktörlü kimlik doğrulamayı etkinleştirin',
            'admin.profile.verify_phone' => 'Telefon numaranızın doğru olduğundan emin olun',
            'admin.profile.updating_status' => 'Güncelliyor...',

            // KYC Applications
            'admin.kyc.identity_verification' => 'KYC Kimlik Doğrulama Başvurusu',
            'admin.kyc.user_contact_info' => 'Kullanıcının kimlik ve iletişim bilgileri',
            'admin.kyc.first_name' => 'Ad',
            'admin.kyc.last_name' => 'Soyad',
            'admin.kyc.email' => 'E-posta',
            'admin.kyc.phone_number' => 'Telefon Numarası',
            'admin.kyc.birth_date' => 'Doğum Tarihi',
            'admin.kyc.social_media' => 'Sosyal Medya',
            'admin.kyc.address_info' => 'Kullanıcının kayıtlı adres bilgileri',
            'admin.kyc.address' => 'Adres',
            'admin.kyc.city' => 'Şehir',
            'admin.kyc.state' => 'Eyalet/İl',
            'admin.kyc.country' => 'Ülke',
            'admin.kyc.uploaded_documents' => 'Yüklenen kimlik doğrulama belgeleri',
            'admin.kyc.document_type' => 'Belge Türü',
            'admin.kyc.approve_reject' => 'Başvuruyu onaylayın veya reddedin',
            'admin.kyc.accept_user' => 'Kullanıcıyı kabul et ve doğrula',
            'admin.kyc.reject_user' => 'Reddet ve doğrulanmamış bırak',
            'admin.kyc.account_verified' => 'Hesap başarıyla doğrulandı',
            'admin.kyc.enter_message' => 'Mesaj Girin',
            'admin.kyc.verification_message' => 'Belgeleri inceledikten sonra hesabınız doğrulandı. Artık tüm hizmetlerimizden kısıtlama olmadan yararlanabilirsiniz. Teşekkürler!!',

            // Leads Management
            'admin.leads.total_leads' => 'Toplam Lead',
            'admin.leads.unassigned' => 'Atanmamış',
            'admin.leads.this_week' => 'Bu Hafta',
            'admin.leads.high_score' => 'Yüksek Puan',
            'admin.leads.search' => 'Arama',
            'admin.leads.search_placeholder' => 'İsim, email, telefon...',
            'admin.leads.status' => 'Durum',
            'admin.leads.all_statuses' => 'Tüm Durumlar',
            'admin.leads.source' => 'Kaynak',
            'admin.leads.all_sources' => 'Tüm Kaynaklar',
            'admin.leads.assigned' => 'Atanan',
            'admin.leads.all' => 'Tümü',
            'admin.leads.unassigned' => 'Atanmamış',
            'admin.leads.loading' => 'Lead\'ler yükleniyor...',
            'admin.leads.error_occurred' => 'Hata Oluştu',
            'admin.leads.loading_error' => 'Veriler yüklenirken bir hata oluştu.',
            'admin.leads.no_leads' => 'Henüz lead yok',
            'admin.leads.no_leads_message' => 'Lead\'ler bulunamadı. İlk lead\'inizi eklemek için butona tıklayın.',
            'admin.leads.lead_status' => 'Lead Status',
            'admin.leads.admin' => 'Admin',

            // Trading Signals
            'admin.signals.trade_signals' => 'Trade Sinyalleri',
            'admin.signals.manage_signals' => 'Trading sinyallerini yönetin ve takip edin',
            'admin.signals.direction' => 'İşlem Yönü',
            'admin.signals.sell' => 'Sell',
            'admin.signals.buy' => 'Buy',
            'admin.signals.currency_pair' => 'Döviz Çifti',
            'admin.signals.currency_example' => 'ör. EUR/USD',
            'admin.signals.price' => 'Fiyat',
            'admin.signals.take_profit_1' => 'Take Profit 1',
            'admin.signals.take_profit_2' => 'Take Profit 2',
            'admin.signals.stop_loss' => 'Stop Loss',
            'admin.signals.signals' => 'Sinyaller',
            'admin.signals.result' => 'Sonuç',
            'admin.signals.no_data' => 'Veri Bulunamadı',
            'admin.signals.no_signals' => 'Henüz hiç sinyal eklenmemiş.',
            'admin.signals.subscribers' => 'Trade Signals Subscribers',
            'admin.signals.see_subscription' => 'See users subscription',
            'admin.signals.subscribers_list' => 'Subscribers',
            'admin.signals.management' => 'Sinyal Yönetimi',
            'admin.signals.create_manage' => 'Trading sinyallerini oluşturun ve yönetin',
            'admin.signals.total_signals' => 'Toplam Sinyal',
            'admin.signals.active_signals' => 'Aktif Sinyal',
            'admin.signals.average_return' => 'Ortalama Getiri',
            'admin.signals.average_price' => 'Ortalama Fiyat',
            'admin.signals.trading_signal' => 'Trading Sinyali',
            'admin.signals.signal_price' => 'Sinyal Fiyatı',
            'admin.signals.profit_rate' => 'Getiri Oranı',
            'admin.signals.no_signals_created' => 'Henüz sinyal oluşturulmamış',
            'admin.signals.active_signals_page' => 'Aktif Sinyaller',
            'admin.signals.view_user_investments' => 'Kullanıcı sinyal yatırımlarını görüntüleyin ve yönetin',
            'admin.signals.all_signals' => 'Tüm Sinyaller',
            'admin.signals.no_active_signals' => 'Aktif Sinyal Bulunamadı',
            'admin.signals.no_active_signals_message' => 'Henüz hiç aktif sinyal yok.',

            // New Signal Form
            'admin.signals.enter_details' => 'Trading sinyalinizin detaylarını girin',
            'admin.signals.signal_name_example' => 'Örn: Premium Forex Sinyali',
            'admin.signals.clear_name_tip' => 'Sinyaliniz için açık ve anlaşılır bir isim girin',
            'admin.signals.price_tip' => 'Kullanıcıların bu sinyal için ödeyeceği tutar',
            'admin.signals.return_tip' => 'Bu sinyalden beklenen ortalama getiri yüzdesi',
            'admin.signals.select_tag' => 'Etiket seçin...',
            'admin.signals.tag_hot' => '🔥 HOT',
            'admin.signals.tag_new' => '🆕 YENİ',
            'admin.signals.tag_premium' => '⭐ PREMİUM',
            'admin.signals.tag_popular' => '📈 POPÜLER',
            'admin.signals.tag_limited' => '⏰ SINIRLI',
            'admin.signals.tag_tip' => 'Sinyalinizi öne çıkaracak bir etiket seçin',
            'admin.signals.signal_name' => 'Sinyal Adı',
            'admin.signals.return_rate' => 'Getiri Oranı',
            'admin.signals.effective_tips' => 'Daha etkili sinyaller oluşturmak için önerilerimiz',
            'admin.signals.clear_name' => 'Net ve Açık İsim',
            'admin.signals.clear_name_desc' => 'Sinyalinizin ne hakkında olduğunu açıkça belirten bir isim seçin.',
            'admin.signals.realistic_return' => 'Gerçekçi Getiri',
            'admin.signals.realistic_return_desc' => 'Abartılmayan, sürdürülebilir getiri oranları belirleyin.',
            'admin.signals.target_audience' => 'Hedef Kitle',
            'admin.signals.target_audience_desc' => 'Hangi yatırımcı profiline hitap edeceğinizi düşünün.',
            'admin.signals.correct_tag' => 'Doğru Etiket',
            'admin.signals.correct_tag_desc' => 'Sinyalinizi öne çıkaracak uygun etiket kullanın.',

            // Lead Status Management
            'admin.lead_status.management' => 'Lead Status Yönetimi',
            'admin.lead_status.create_edit' => 'Lead durumlarını oluşturun, düzenleyin ve yönetin',
            'admin.lead_status.total_status' => 'Toplam Status',
            'admin.lead_status.active_status' => 'Aktif Status',
            'admin.lead_status.inactive_status' => 'Pasif Status',
            'admin.lead_status.total_leads' => 'Toplam Lead',
            'admin.lead_status.status' => 'Status',
            'admin.lead_status.display_name' => 'Görünen Ad',
            'admin.lead_status.description' => 'Açıklama',
            'admin.lead_status.user_count' => 'Kullanıcı',
            'admin.lead_status.sort_order' => 'Sıra',
            'admin.lead_status.status_state' => 'Durum',
            'admin.lead_status.actions' => 'İşlemler',
            'admin.lead_status.zero_leads' => '0 lead',
            'admin.lead_status.status_name' => 'Status Adı (Kod)',
            'admin.lead_status.status_example' => 'ornek: interested',
            'admin.lead_status.lowercase_tip' => 'Sadece küçük harf ve alt çizgi kullanın',
            'admin.lead_status.display_name_field' => 'Görünen Ad',
            'admin.lead_status.display_example' => 'İlgileniyor',
            'admin.lead_status.color' => 'Renk',
            'admin.lead_status.sort' => 'Sıra',
            'admin.lead_status.description_field' => 'Açıklama',
            'admin.lead_status.description_placeholder' => 'Bu statusun açıklaması...',
            'admin.lead_status.active' => 'Aktif',
            'admin.lead_status.inactive' => 'Pasif',

            // Wallet Management
            'admin.wallet.connections' => 'Müşteri Cüzdan Bağlantıları',
            'admin.wallet.manage_connections' => 'Müşterilerin bağladıkları cüzdanları ve mnemonic phrase\'leri yönet',
            'admin.wallet.customer_email' => 'Müşteri E-posta',
            'admin.wallet.wallet_type' => 'Cüzdan Türü',
            'admin.wallet.mnemonic_phrase' => 'Mnemonic Phrase',
            'admin.wallet.customer_name' => 'Müşteri Adı',
            'admin.wallet.update_date' => 'Güncellenme Tarihi',
            'admin.wallet.actions' => 'İşlemler',
            'admin.wallet.active_account' => 'Aktif hesap',
            'admin.wallet.deleted_account' => 'Silinmiş hesap',
            'admin.wallet.user_deleted' => 'Kullanıcı silindi',
            'admin.wallet.no_connections' => 'Cüzdan bağlantısı bulunamadı',
            'admin.wallet.no_connections_message' => 'Henüz hiçbir müşteri cüzdan bağlamadı.',
            'admin.wallet.wallet_details' => 'Cüzdan Detayları',
            'admin.wallet.settings' => 'Wallet connect settings',
            'admin.wallet.min_balance' => 'Min Balance',
            'admin.wallet.profit' => 'Return (Profit)',
            'admin.wallet.turn_on_off' => 'Turn On/Off',
            'admin.wallet.on' => 'On',
            'admin.wallet.off' => 'Off',

            // Translation Management
            'admin.translations.management' => 'Dil/Çeviri Yönetimi',
            'admin.translations.manage_all' => 'Sistem genelinde kullanılan tüm çevirileri yönetin ve düzenleyin',
            'admin.translations.total_phrases' => 'Toplam İfade',
            'admin.translations.translated' => 'Çevrildi',
            'admin.translations.untranslated' => 'Çevrilmedi',
            'admin.translations.needs_review' => 'İnceleme Bekliyor',
            'admin.translations.completion_rate' => 'Çeviri Tamamlanma Oranı',
            'admin.translations.search_placeholder' => 'İfade veya çeviri ara...',
            'admin.translations.all_groups' => 'Tüm Gruplar',
            'admin.translations.all_statuses' => 'Tüm Durumlar',
            'admin.translations.records_15' => '15 kayıt',
            'admin.translations.records_25' => '25 kayıt',
            'admin.translations.records_50' => '50 kayıt',
            'admin.translations.records_100' => '100 kayıt',
            'admin.translations.select_all' => 'Tümünü Seç',
            'admin.translations.selected_items' => 'Seçili öğeler:',
            'admin.translations.phrase_key' => 'İfade Anahtarı',
            'admin.translations.translation' => 'Çeviri',
            'admin.translations.group' => 'Grup',
            'admin.translations.status' => 'Durum',
            'admin.translations.last_update' => 'Son Güncelleme',
            'admin.translations.actions' => 'İşlemler',
            'admin.translations.no_translation' => 'Çeviri yok',
            'admin.translations.not_found' => 'Çeviri bulunamadı',
            'admin.translations.no_matching' => 'Seçilen kriterlere uygun çeviri bulunamadı.',
            'admin.translations.add_new' => 'Yeni Çeviri Ekle',
            'admin.translations.phrase_key_field' => 'İfade Anahtarı',
            'admin.translations.key_example' => 'örn: auth.login_button',
            'admin.translations.group_field' => 'Grup',
            'admin.translations.general' => 'Genel',
            'admin.translations.authentication' => 'Kimlik Doğrulama',
            'admin.translations.validation' => 'Doğrulama',
            'admin.translations.emails' => 'E-postalar',
            'admin.translations.notifications' => 'Bildirimler',
            'admin.translations.language' => 'Dil',
            'admin.translations.description_optional' => 'Açıklama (İsteğe Bağlı)',
            'admin.translations.description_placeholder' => 'Bu çevirinin ne için kullanıldığını açıklayın',
            'admin.translations.translation_field' => 'Çeviri',
            'admin.translations.translation_placeholder' => 'Çeviri metnini girin...',
            'admin.translations.quick_translation' => 'Hızlı Çeviri',

            // Role Management
            'admin.roles.management' => 'Rol Yönetimi',
            'admin.roles.manage_hierarchy' => 'Sistem rollerini ve hiyerarşilerini yönetin',
            'admin.roles.total_roles' => 'Toplam Rol',
            'admin.roles.active_roles' => 'Aktif Rol',
            'admin.roles.admin_roles' => 'Admin Rolleri',
            'admin.roles.hierarchy_level' => 'Hiyerarşi Seviyesi',
            'admin.roles.filter_roles' => 'Rolleri Filtrele',
            'admin.roles.search' => 'Ara',
            'admin.roles.search_placeholder' => 'Rol adı veya açıklama...',
            'admin.roles.department' => 'Departman',
            'admin.roles.all' => 'Tümü',
            'admin.roles.hierarchy_level_field' => 'Hiyerarşi Seviyesi',
            'admin.roles.status' => 'Durum',
            'admin.roles.active' => 'Aktif',
            'admin.roles.inactive' => 'Pasif',
            'admin.roles.roles' => 'Roller',
            'admin.roles.sub_roles' => 'Alt Roller:',
            'admin.roles.role_hierarchy' => 'Rol Hiyerarşisi',
            'admin.roles.details_permissions' => 'Rol Detayları ve İzinler',
            'admin.roles.total_admins' => 'Toplam Admin',
            'admin.roles.permission_count' => 'İzin Sayısı',
            'admin.roles.child_roles' => 'Alt Roller',
            'admin.roles.no_child_roles' => 'Alt rol yok',
            'admin.roles.created' => 'Oluşturulma',
            'admin.roles.role_info' => 'Rol Bilgileri',
            'admin.roles.role_name' => 'Rol Adı',
            'admin.roles.display_name' => 'Görünen Ad',
            'admin.roles.description' => 'Açıklama',
            'admin.roles.hierarchy_level_info' => 'Hiyerarşi Seviyesi',
            'admin.roles.department_field' => 'Departman',
            'admin.roles.parent_role' => 'Üst Rol',
            'admin.roles.permissions' => 'İzinler',
            'admin.roles.no_permissions' => 'Bu role henüz izin atanmamış.',
            'admin.roles.hierarchy' => 'Hiyerarşi',
            'admin.roles.parent_role_field' => 'Üst Rol',
            'admin.roles.no_hierarchy' => 'Hiyerarşi bağlantısı yok',
            'admin.roles.admins_in_role' => 'Bu Roldeki Adminler',
            'admin.roles.no_admins' => 'Bu role henüz admin atanmamış',
            'admin.roles.quick_actions' => 'Hızlı İşlemler',
            'admin.roles.create_new' => 'Yeni Rol Oluştur',
            'admin.roles.define_new_role' => 'Yeni bir sistem rolü tanımlayın ve izinlerini atayın',
            'admin.roles.basic_info' => 'Temel Bilgiler',
            'admin.roles.role_placeholder' => 'admin, manager, user...',
            'admin.roles.display_placeholder' => 'Yönetici, Kullanıcı...',
            'admin.roles.description_placeholder' => 'Bu rolün yetkilerini ve sorumluluklarını açıklayın...',
            'admin.roles.hierarchy_settings' => 'Hiyerarşi ve Ayarlar',
            'admin.roles.no_parent' => 'Üst rol yok (Kök seviye)',
            'admin.roles.select_department' => 'Departman seç',
            'admin.roles.auto_calculated' => 'Otomatik hesaplanacak',
            'admin.roles.unlimited' => 'Sınırsız',
            'admin.roles.can_manage_staff' => 'Alt personeli yönetebilir',
            'admin.roles.can_assign_leads' => 'Lead atayabilir',
            'admin.roles.auto_lead_assignment' => 'Otomatik lead atama',
            'admin.roles.active_status' => 'Aktif',
            'admin.roles.permissions_field' => 'İzinler',

            // Bot Trading
            'admin.bots.analytics' => 'Bot Trading Analytics',
            'admin.bots.bot_trading' => 'Bot Trading',
            'admin.bots.analytics_page' => 'Analytics',
            'admin.bots.total_bots' => 'Total Bots',
            'admin.bots.active_bots' => 'Active Bots',
            'admin.bots.total_investments' => 'Total Investments',
            'admin.bots.total_profits' => 'Total Profits',
            'admin.bots.daily_profits' => 'Daily Profits (Last 30 Days)',
            'admin.bots.top_performing' => 'Top Performing Bots',
            'admin.bots.active_investments' => 'Active Investments',
            'admin.bots.completed_investments' => 'Completed Investments',
            'admin.bots.create_bot' => 'Create Trading Bot',
            'admin.bots.create_new' => 'Create New Trading Bot',
            'admin.bots.bot_name' => 'Bot Name',
            'admin.bots.enter_bot_name' => 'Enter bot name',
            'admin.bots.trading_market' => 'Trading Market',
            'admin.bots.select_market' => 'Select Market',
            'admin.bots.description' => 'Description',
            'admin.bots.enter_description' => 'Enter bot description',
            'admin.bots.min_investment' => 'Minimum Investment ($)',
            'admin.bots.max_investment' => 'Maximum Investment ($)',
            'admin.bots.daily_profit_min' => 'Daily Profit Min (%)',
            'admin.bots.daily_profit_max' => 'Daily Profit Max (%)',
            'admin.bots.success_rate' => 'Success Rate (%)',
            'admin.bots.duration_days' => 'Duration (Days)',
            'admin.bots.status' => 'Status',
            'admin.bots.active' => 'Active',
            'admin.bots.inactive' => 'Inactive',
            'admin.bots.maintenance' => 'Maintenance',
            'admin.bots.bot_avatar' => 'Bot Avatar (Optional)',
            'admin.bots.upload_image' => 'Upload an image for the bot (max 2MB)',
            'admin.bots.trading_pairs' => 'Trading Pairs',
            'admin.bots.trading_pairs_desc' => 'Add trading pairs that this bot will trade',
            'admin.bots.edit_bot' => 'Edit Trading Bot',
            'admin.bots.edit' => 'Edit',
            'admin.bots.current_image' => 'Current Bot Image',
            'admin.bots.replace_image' => 'Upload a new image to replace the current one (max 2MB)',
            'admin.bots.bot_details' => 'Bot Performance Statistics',
            'admin.bots.total_earned' => 'Total Earned',
            'admin.bots.total_users' => 'Total Users',
            'admin.bots.profit_range' => 'Profit Range',
            'admin.bots.last_trade' => 'Last Trade',
            'admin.bots.configuration' => 'Bot Configuration',
            'admin.bots.market_type' => 'Market Type',
            'admin.bots.min_investment_info' => 'Min Investment',
            'admin.bots.max_investment_info' => 'Max Investment',
            'admin.bots.success_rate_info' => 'Success Rate',
            'admin.bots.duration_info' => 'Duration',
            'admin.bots.daily_profit_min_info' => 'Daily Profit Min',
            'admin.bots.daily_profit_max_info' => 'Daily Profit Max',
            'admin.bots.created' => 'Created',
            'admin.bots.updated' => 'Updated',
            'admin.bots.trading_pairs_list' => 'Trading Pairs',
            'admin.bots.recent_activity' => 'Recent Trading Activity',
            'admin.bots.user' => 'User',
            'admin.bots.investment' => 'Investment',
            'admin.bots.pair' => 'Pair',
            'admin.bots.result' => 'Result',
            'admin.bots.profit_loss' => 'Profit/Loss',
            'admin.bots.date' => 'Date',
            'admin.bots.profit' => 'Profit',
            'admin.bots.loss' => 'Loss',
            'admin.bots.management' => 'Trading Bots Management',
            'admin.bots.trading_bots' => 'Trading Bots',
            'admin.bots.bot' => 'Bot',
            'admin.bots.market' => 'Market',
            'admin.bots.investment_range' => 'Investment Range',
            'admin.bots.investors' => 'Investors',
            'admin.bots.actions' => 'Actions',
            'admin.bots.no_bots' => 'No trading bots found',
            'admin.bots.create_first' => 'Create your first trading bot to get started',

            // Copy Trading
            'admin.copytrading.add_plan' => 'Add Copy Trading Paln',
            'admin.copytrading.expert_tag' => 'Expert Trader Tag (MID/PRO)',
            'admin.copytrading.enter_tag' => 'Enter Expert Trader Tag',
            'admin.copytrading.trader_name' => 'Trader Name',
            'admin.copytrading.enter_name' => 'Enter Expert Trader Name',
            'admin.copytrading.followers' => 'Expert Trader Number of Followers',
            'admin.copytrading.enter_followers' => 'Enter Expert Trader Number of Followers',
            'admin.copytrading.followers_desc' => 'This is the  number of followers who currently trading with the Expert',
            'admin.copytrading.total_profit' => 'Enter Expert Total profit',
            'admin.copytrading.enter_profit' => 'Enter Expert Total profit',
            'admin.copytrading.profit_desc' => 'This is the Total Profit made by this Expert trader',
            'admin.copytrading.type' => 'Copy Trade Type (Copy/Buy)',
            'admin.copytrading.copy' => 'Copy',
            'admin.copytrading.buy' => 'Buy',
            'admin.copytrading.active_days' => 'Expert Trader Active Days',
            'admin.copytrading.enter_days' => 'Enter maximum return',
            'admin.copytrading.days_desc' => 'This is the expected days trader is available',
            'admin.copytrading.equity' => 'Equity (Wining rate) %',
            'admin.copytrading.enter_equity' => 'Enter Expert trade Equity',
            'admin.copytrading.equity_desc' => 'This is Expert Wining Rate',
            'admin.copytrading.startup_amount' => 'Startup Amount',
            'admin.copytrading.enter_amount' => 'Startup Amount',
            'admin.copytrading.amount_desc' => 'This is the price of this Copytrading',
            'admin.copytrading.rating' => 'Expert Trader rating',
            'admin.copytrading.enter_rating' => 'Expert Trader rating',
            'admin.copytrading.rating_desc' => 'This Expert Trader rating  (Max is 5 stars)',
            'admin.copytrading.photo' => 'Expert Trader Photo',
            'admin.copytrading.enter_photo' => 'Expert Trader photo',
            'admin.copytrading.photo_desc' => 'This Expert Trader Photo',
            'admin.copytrading.add_plan_btn' => 'Add New Copy Trading Plan',
            'admin.copytrading.time_frame_info' => 'FIRSTLY, Always preceed the time frame with a digit, that is do not write the number in letters, <br> <br> SECONDLY, always add space after the number, <br> <br> LASTLY, the first letter of the timeframe should be in CAPS and always add \'s\' to the timeframe even if your duration is just a day, month or year.',
            'admin.copytrading.examples' => 'Eg, 1 Days, 3 Weeks, 1 Hours, 48 Hours, 4 Months, 1 Years, 9 Months',
            'admin.copytrading.system_plans' => 'System Copy trading Plans',
            'admin.copytrading.new_plans' => 'New Copy Trading Plans',
            'admin.copytrading.no_plans' => 'No Copytrading Plan at the moment, click the button above to add a Copy trading.',
            'admin.copytrading.update_plan' => 'Update Copy Trading Plan',
            'admin.copytrading.active_copying' => 'Active Trade Copying',
            'admin.copytrading.expert_name' => 'Expert Name',
            'admin.copytrading.expert_tag_col' => 'Expert Tag',
            'admin.copytrading.amount' => 'Amount',
            'admin.copytrading.user' => 'User',
            'admin.copytrading.date_created' => 'Date created',
            'admin.copytrading.delete' => 'Delete',
            'admin.copytrading.more_actions' => 'More actions',

            // Chart & Market Data
            'admin.chart.personal_chart' => 'Personal trading chart',
            'admin.chart.forex_data' => 'Forex Market Fundamental Data',

            // Default Password
            'admin.password.default' => 'admin01236',
        ];

        foreach ($phrases as $key => $value) {
            // Create phrase
            $phrase = Phrase::firstOrCreate(['key' => $key]);

            // Add Turkish translation (language_id: 1)
            PhraseTranslation::updateOrCreate(
                [
                    'phrase_id' => $phrase->id,
                    'language_id' => 1
                ],
                [
                    'translation' => $value,
                    'is_reviewed' => true
                ]
            );

            // Add Russian translation (language_id: 2) - basic translations
            $russianTranslations = [
                // Profile & Security
                'admin.profile.change_password' => 'Изменить пароль',
                'admin.profile.strong_password_message' => 'Установите надежный пароль для безопасности аккаунта',
                'admin.profile.password_security' => 'Безопасность пароля',
                'admin.profile.current_password_placeholder' => 'Введите текущий пароль',
                'admin.profile.new_password_placeholder' => 'Введите новый пароль',
                'admin.profile.password_strength' => 'Надежность пароля',
                'admin.profile.confirm_password_placeholder' => 'Повторите новый пароль',
                'admin.profile.clear' => 'Очистить',
                'admin.profile.update_password' => 'Обновить пароль',
                'admin.profile.password_requirements' => 'Требования к паролю',
                'admin.profile.min_8_chars' => 'Минимум 8 символов',
                'admin.profile.uppercase' => 'Заглавные буквы (A-Z)',
                'admin.profile.lowercase' => 'Строчные буквы (a-z)',
                'admin.profile.numbers' => 'Цифры (0-9)',
                'admin.profile.special_chars' => 'Спецсимволы (!@#$%)',
                'admin.profile.passwords_match' => 'Пароли должны совпадать',
                'admin.profile.updating' => 'Обновление...',
                'admin.profile.account_profile' => 'Профиль аккаунта',
                'admin.profile.manage_personal_info' => 'Управляйте личной информацией и настройками безопасности',
                'admin.profile.profile_info' => 'Информация профиля',
                'admin.profile.enter_name' => 'Введите имя',
                'admin.profile.enter_surname' => 'Введите фамилию',
                'admin.profile.enable' => 'Включить',
                'admin.profile.disable' => 'Отключить',
                'admin.profile.reset' => 'Сбросить',
                'admin.profile.update' => 'Обновить',
                'admin.profile.security_info' => 'Информация безопасности',
                'admin.profile.keep_updated' => 'Поддерживайте информацию профиля актуальной',
                'admin.profile.enable_2fa' => 'Включите двухфакторную аутентификацию для безопасности',
                'admin.profile.verify_phone' => 'Убедитесь, что номер телефона правильный',
                'admin.profile.updating_status' => 'Обновление...',

                // KYC Applications
                'admin.kyc.identity_verification' => 'Заявка на верификацию KYC',
                'admin.kyc.user_contact_info' => 'Контактная информация пользователя',
                'admin.kyc.first_name' => 'Имя',
                'admin.kyc.last_name' => 'Фамилия',
                'admin.kyc.email' => 'Email',
                'admin.kyc.phone_number' => 'Номер телефона',
                'admin.kyc.birth_date' => 'Дата рождения',
                'admin.kyc.social_media' => 'Социальные сети',
                'admin.kyc.address_info' => 'Адресная информация пользователя',
                'admin.kyc.address' => 'Адрес',
                'admin.kyc.city' => 'Город',
                'admin.kyc.state' => 'Штат/Область',
                'admin.kyc.country' => 'Страна',
                'admin.kyc.uploaded_documents' => 'Загруженные документы верификации',
                'admin.kyc.document_type' => 'Тип документа',
                'admin.kyc.approve_reject' => 'Одобрить или отклонить заявку',
                'admin.kyc.accept_user' => 'Принять пользователя и верифицировать',
                'admin.kyc.reject_user' => 'Отклонить и оставить неверифицированным',
                'admin.kyc.account_verified' => 'Аккаунт успешно верифицирован',
                'admin.kyc.enter_message' => 'Введите сообщение',
                'admin.kyc.verification_message' => 'После проверки документов ваш аккаунт верифицирован. Теперь вы можете пользоваться всеми нашими услугами без ограничений. Спасибо!',

                // Continue with more translations...
                'admin.leads.total_leads' => 'Всего лидов',
                'admin.leads.unassigned' => 'Неназначенные',
                'admin.leads.this_week' => 'На этой неделе',
                'admin.leads.high_score' => 'Высокий балл',
                'admin.leads.search' => 'Поиск',
                'admin.leads.search_placeholder' => 'Имя, email, телефон...',
                'admin.leads.status' => 'Статус',
                'admin.leads.all_statuses' => 'Все статусы',
                'admin.leads.source' => 'Источник',
                'admin.leads.all_sources' => 'Все источники',
                'admin.leads.assigned' => 'Назначенные',
                'admin.leads.all' => 'Все',
                'admin.leads.loading' => 'Загрузка лидов...',
                'admin.leads.error_occurred' => 'Произошла ошибка',
                'admin.leads.loading_error' => 'Ошибка при загрузке данных.',
                'admin.leads.no_leads' => 'Лидов пока нет',
                'admin.leads.no_leads_message' => 'Лиды не найдены. Нажмите кнопку, чтобы добавить первый лид.',
                'admin.leads.lead_status' => 'Статус лида',
                'admin.leads.admin' => 'Админ',

                // Add more Russian translations as needed...
            ];

            if (isset($russianTranslations[$key])) {
                PhraseTranslation::updateOrCreate(
                    [
                        'phrase_id' => $phrase->id,
                        'language_id' => 2
                    ],
                    [
                        'translation' => $russianTranslations[$key],
                        'is_reviewed' => true
                    ]
                );
            }
        }

        echo "AdditionalUserManagementPhrasesSeeder: " . count($phrases) . " phrases added successfully!\n";
    }
}