<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Phrase;
use App\Models\PhraseTranslation;

class MissingUserManagementPhrasesSeeder extends Seeder
{
    /**
     * Eksik User Management Admin Pages phrase'lerini database'e ekler
     */
    public function run()
    {
        $phrases = [
            // admin.users - Eksik Kullanıcı Yönetimi Terimleri
            'admin.users.admin_panel' => ['tr' => 'Yönetici Paneli', 'ru' => 'Панель администратора'],
            'admin.users.manage_and_control_admins' => ['tr' => 'Yöneticileri yönet ve kontrol et', 'ru' => 'Управление и контроль администраторов'],
            'admin.users.no_phone' => ['tr' => 'Telefon yok', 'ru' => 'Нет телефона'],
            'admin.users.user_management' => ['tr' => 'Kullanıcı Yönetimi', 'ru' => 'Управление пользователями'],
            'admin.users.view_and_manage_platform_users' => ['tr' => 'Platform kullanıcılarını görüntüle ve yönet', 'ru' => 'Просмотр и управление пользователями платформы'],
            'admin.users.new_user' => ['tr' => 'Yeni Kullanıcı', 'ru' => 'Новый пользователь'],
            'admin.users.user' => ['tr' => 'Kullanıcı', 'ru' => 'Пользователь'],
            'admin.users.email' => ['tr' => 'E-posta', 'ru' => 'Email'],
            'admin.users.phone' => ['tr' => 'Telefon', 'ru' => 'Телефон'],
            'admin.users.date' => ['tr' => 'Tarih', 'ru' => 'Дата'],
            'admin.users.utm_source' => ['tr' => 'UTM Kaynak', 'ru' => 'UTM источник'],
            'admin.users.status' => ['tr' => 'Durum', 'ru' => 'Статус'],
            'admin.users.user_not_found' => ['tr' => 'Kullanıcı bulunamadı', 'ru' => 'Пользователь не найден'],
            'admin.users.no_users_added_yet' => ['tr' => 'Henüz kullanıcı eklenmedi', 'ru' => 'Пользователи еще не добавлены'],
            'admin.users.users_selected' => ['tr' => 'kullanıcı seçildi', 'ru' => 'пользователей выбрано'],
            'admin.users.add_new_user' => ['tr' => 'Yeni Kullanıcı Ekle', 'ru' => 'Добавить нового пользователя'],
            'admin.users.add_user' => ['tr' => 'Kullanıcı Ekle', 'ru' => 'Добавить пользователя'],
            'admin.users.never' => ['tr' => 'Hiçbir zaman', 'ru' => 'Никогда'],
            'admin.users.verified' => ['tr' => 'Doğrulanmış', 'ru' => 'Верифицирован'],
            'admin.users.unassigned' => ['tr' => 'Atanmamış', 'ru' => 'Не назначен'],
            'admin.users.source' => ['tr' => 'Kaynak', 'ru' => 'Источник'],
            'admin.users.campaign' => ['tr' => 'Kampanya', 'ru' => 'Кампания'],
            'admin.users.no_utm_info' => ['tr' => 'UTM bilgisi yok', 'ru' => 'Нет UTM информации'],
            'admin.users.no_name' => ['tr' => 'İsim yok', 'ru' => 'Нет имени'],
            'admin.users.users_found' => ['tr' => 'kullanıcı bulundu', 'ru' => 'пользователей найдено'],
            'admin.users.users_showing' => ['tr' => 'kullanıcı gösteriliyor', 'ru' => 'пользователей показано'],
            'admin.users.view_edit_manage_users' => ['tr' => 'Kullanıcıları görüntüle, düzenle ve yönet', 'ru' => 'Просмотр, редактирование и управление пользователями'],
            'admin.users.total' => ['tr' => 'Toplam', 'ru' => 'Всего'],
            'admin.users.premium' => ['tr' => 'Premium', 'ru' => 'Премиум'],
            'admin.users.vip' => ['tr' => 'VIP', 'ru' => 'ВИП'],
            'admin.users.admin_assignment' => ['tr' => 'Admin Ataması', 'ru' => 'Назначение администратора'],
            'admin.users.remove_assignment' => ['tr' => 'Atamayı Kaldır', 'ru' => 'Удалить назначение'],
            'admin.users.bulk_status_change' => ['tr' => 'Toplu Durum Değişikliği', 'ru' => 'Массовое изменение статуса'],
            'admin.users.new_lead_status' => ['tr' => 'Yeni Lead Durumu', 'ru' => 'Новый статус лида'],
            'admin.users.no_users_added_or_found' => ['tr' => 'Henüz kullanıcı eklenmedi veya bulunamadı', 'ru' => 'Пользователи еще не добавлены или не найдены'],
            'admin.users.add_new_admin' => ['tr' => 'Yeni Admin Ekle', 'ru' => 'Добавить нового администратора'],
            'admin.users.add_new_admin_description' => ['tr' => 'Sisteme yeni yönetici ekleyin ve yetkilendirin', 'ru' => 'Добавьте нового администратора в систему и авторизуйте его'],
            'admin.users.admin_information' => ['tr' => 'Yönetici Bilgileri', 'ru' => 'Информация об администраторе'],
            'admin.users.email_address' => ['tr' => 'E-posta Adresi', 'ru' => 'Адрес электронной почты'],
            'admin.users.phone_number' => ['tr' => 'Telefon Numarası', 'ru' => 'Номер телефона'],
            'admin.users.admin_type' => ['tr' => 'Admin Türü', 'ru' => 'Тип администратора'],
            'admin.users.super_admin' => ['tr' => 'Süper Admin', 'ru' => 'Супер администратор'],
            'admin.users.admin' => ['tr' => 'Admin', 'ru' => 'Администратор'],
            'admin.users.conversion_agent' => ['tr' => 'Dönüştürme Temsilcisi', 'ru' => 'Агент по конверсии'],
            'admin.users.super_admin_description' => ['tr' => 'Tüm yetkilere sahip', 'ru' => 'Имеет все полномочия'],
            'admin.users.admin_description' => ['tr' => 'Sınırlı yetkilere sahip', 'ru' => 'Ограниченные полномочия'],
            'admin.users.conversion_agent_description' => ['tr' => 'Lead dönüştürme yetkisi', 'ru' => 'Права конверсии лидов'],
            'admin.users.save_user' => ['tr' => 'Kullanıcıyı Kaydet', 'ru' => 'Сохранить пользователя'],
            'admin.users.user_details_title' => ['tr' => 'Kullanıcı Detayları', 'ru' => 'Детали пользователя'],
            'admin.users.user_details_description' => ['tr' => 'Kullanıcı bilgilerini görüntüle ve yönet', 'ru' => 'Просмотр и управление информацией о пользователе'],
            'admin.users.assigned_admin' => ['tr' => 'Atanan Admin', 'ru' => 'Назначенный администратор'],
            'admin.users.user_information' => ['tr' => 'Kullanıcı Bilgileri', 'ru' => 'Информация о пользователе'],
            'admin.users.no_transactions_yet' => ['tr' => 'Henüz işlem yok', 'ru' => 'Пока нет транзакций'],
            'admin.users.no_transactions_description' => ['tr' => 'Bu kullanıcı henüz herhangi bir işlem yapmadı', 'ru' => 'Этот пользователь еще не совершал никаких транзакций'],
            'admin.users.average_balance' => ['tr' => 'Ortalama Bakiye', 'ru' => 'Средний баланс'],
            'admin.users.type' => ['tr' => 'Tür', 'ru' => 'Тип'],
            'admin.users.admin_selection' => ['tr' => 'Admin Seçimi', 'ru' => 'Выбор администратора'],

            // admin.customers - Eksik Müşteri Yönetimi Terimleri  
            'admin.customers.customer' => ['tr' => 'Müşteri', 'ru' => 'Клиент'],
            'admin.customers.active_customers' => ['tr' => 'Aktif Müşteriler', 'ru' => 'Активные клиенты'],
            'admin.customers.customer_name' => ['tr' => 'Müşteri Adı', 'ru' => 'Имя клиента'],
            'admin.customers.customers_showing' => ['tr' => 'müşteri gösteriliyor', 'ru' => 'клиентов показано'],
            'admin.customers.no_customers_yet' => ['tr' => 'Henüz müşteri yok', 'ru' => 'Клиентов пока нет'],
            'admin.customers.kyc_status' => ['tr' => 'KYC Durumu', 'ru' => 'Статус KYC'],
            'admin.customers.transactions' => ['tr' => 'İşlemler', 'ru' => 'Транзакции'],
            'admin.customers.lead_status' => ['tr' => 'Lead Durumu', 'ru' => 'Статус лида'],

            // admin.agents - Yeni Agent Kategorisi
            'admin.agents.agent_customers' => ['tr' => 'Agent Müşterileri', 'ru' => 'Клиенты агента'],
            'admin.agents.agent_customer_list' => ['tr' => 'için müşteri listesi', 'ru' => 'список клиентов для'],
            'admin.agents.agent' => ['tr' => 'Agent', 'ru' => 'Агент'],
            'admin.agents.total_earnings' => ['tr' => 'Toplam Kazanç', 'ru' => 'Общие доходы'],
            'admin.agents.no_assigned_customers' => ['tr' => 'Bu agent\'e henüz müşteri atanmamış', 'ru' => 'Этому агенту пока не назначены клиенты'],

            // admin.investments - Eksik Yatırım Terimleri
            'admin.investments.user_investments' => ['tr' => 'Kullanıcı Yatırımları', 'ru' => 'Инвестиции пользователя'],
            'admin.investments.plan' => ['tr' => 'Plan', 'ru' => 'План'],
            'admin.investments.amount' => ['tr' => 'Tutar', 'ru' => 'Сумма'],
            'admin.investments.active' => ['tr' => 'Aktif', 'ru' => 'Активный'],
            'admin.investments.duration' => ['tr' => 'Süre', 'ru' => 'Длительность'],
            'admin.investments.created_on' => ['tr' => 'Oluşturulma Tarihi', 'ru' => 'Дата создания'],
            'admin.investments.expire_at' => ['tr' => 'Son Kullanma', 'ru' => 'Истекает'],
            'admin.investments.option' => ['tr' => 'Seçenek', 'ru' => 'Опция'],
            'admin.investments.assets' => ['tr' => 'Varlık', 'ru' => 'Актив'],
            'admin.investments.status' => ['tr' => 'Durum', 'ru' => 'Статус'],
            'admin.investments.leverage' => ['tr' => 'Kaldıraç', 'ru' => 'Кредитное плечо'],
            'admin.investments.trade_type' => ['tr' => 'İşlem Türü', 'ru' => 'Тип сделки'],
            'admin.investments.profit_loss' => ['tr' => 'Kar/Zarar', 'ru' => 'Прибыль/Убыток'],
            'admin.investments.buy' => ['tr' => 'Al', 'ru' => 'Купить'],
            'admin.investments.sell' => ['tr' => 'Sat', 'ru' => 'Продать'],
            'admin.investments.no_plan_assigned' => ['tr' => 'Plan atanmadı', 'ru' => 'План не назначен'],
            'admin.investments.earnings' => ['tr' => 'Kazançlar', 'ru' => 'Доходы'],
            'admin.investments.loss' => ['tr' => 'Zarar', 'ru' => 'Убыток'],
            'admin.investments.profit' => ['tr' => 'Kar', 'ru' => 'Прибыль'],
            'admin.investments.trade_mode' => ['tr' => 'İşlem Modu', 'ru' => 'Режим торговли'],

            // admin.accounts - Eksik Hesap Terimleri
            'admin.accounts.balance' => ['tr' => 'Bakiye', 'ru' => 'Баланс'],
            'admin.accounts.bonus' => ['tr' => 'Bonus', 'ru' => 'Бонус'],
            'admin.accounts.status' => ['tr' => 'Hesap Durumu', 'ru' => 'Статус аккаунта'],

            // admin.forms - Eksik Form Terimleri
            'admin.forms.ensure_all_fields_filled' => ['tr' => 'Tüm alanların doğru doldurulduğundan emin olun', 'ru' => 'Убедитесь, что все поля заполнены правильно'],
            'admin.forms.first_name_placeholder' => ['tr' => 'Adınızı girin', 'ru' => 'Введите ваше имя'],
            'admin.forms.last_name_placeholder' => ['tr' => 'Soyadınızı girin', 'ru' => 'Введите вашу фамилию'],
            'admin.forms.email_placeholder' => ['tr' => 'E-posta adresinizi girin', 'ru' => 'Введите ваш email адрес'],
            'admin.forms.phone_placeholder' => ['tr' => 'Telefon numaranızı girin', 'ru' => 'Введите ваш номер телефона'],
            'admin.forms.select_admin_type' => ['tr' => 'Admin türünü seçin', 'ru' => 'Выберите тип администратора'],
            'admin.forms.strong_password_placeholder' => ['tr' => 'Güçlü bir şifre girin', 'ru' => 'Введите надежный пароль'],
            'admin.forms.repeat_password_placeholder' => ['tr' => 'Şifreyi tekrar girin', 'ru' => 'Повторите пароль'],
            'admin.forms.subject' => ['tr' => 'Konu', 'ru' => 'Тема'],
            'admin.forms.message' => ['tr' => 'Mesaj', 'ru' => 'Сообщение'],
            'admin.forms.email_subject_placeholder' => ['tr' => 'E-posta konusunu girin', 'ru' => 'Введите тему письма'],
            'admin.forms.message_placeholder' => ['tr' => 'Mesajınızı yazın', 'ru' => 'Напишите ваше сообщение'],
            'admin.forms.password_confirmation' => ['tr' => 'Şifre Onayı', 'ru' => 'Подтверждение пароля'],
            'admin.forms.not_specified' => ['tr' => 'Belirtilmemiş', 'ru' => 'Не указано'],
            'admin.forms.date_of_birth' => ['tr' => 'Doğum Tarihi', 'ru' => 'Дата рождения'],
            'admin.forms.country' => ['tr' => 'Ülke', 'ru' => 'Страна'],
            'admin.forms.select_admin' => ['tr' => 'Admin Seçin', 'ru' => 'Выберите администратора'],
            'admin.forms.select_status' => ['tr' => 'Durum Seçin', 'ru' => 'Выберите статус'],
            'admin.forms.registration_date' => ['tr' => 'Kayıt Tarihi', 'ru' => 'Дата регистрации'],
            'admin.forms.admin_notes' => ['tr' => 'Admin Notları', 'ru' => 'Заметки администратора'],
            'admin.forms.unknown_admin' => ['tr' => 'Bilinmeyen Admin', 'ru' => 'Неизвестный администратор'],
            'admin.forms.no_notes_yet' => ['tr' => 'Henüz not yok', 'ru' => 'Заметок пока нет'],
            'admin.forms.no_notes_description' => ['tr' => 'Bu kullanıcı için henüz admin notu eklenmemiş', 'ru' => 'Заметки администратора для этого пользователя еще не добавлены'],
            'admin.forms.email' => ['tr' => 'E-posta', 'ru' => 'Email'],
            'admin.forms.phone' => ['tr' => 'Telefon', 'ru' => 'Телефон'],
            'admin.forms.characters' => ['tr' => 'karakter', 'ru' => 'символов'],
            'admin.forms.new_password' => ['tr' => 'Yeni Şifre', 'ru' => 'Новый пароль'],
            'admin.forms.please_select_status' => ['tr' => 'Lütfen durum seçin', 'ru' => 'Пожалуйста, выберите статус'],
            'admin.forms.select_user' => ['tr' => 'Kullanıcı Seç', 'ru' => 'Выберите пользователя'],

            // admin.actions - Eksik Action Terimleri
            'admin.actions.back' => ['tr' => 'Geri', 'ru' => 'Назад'],
            'admin.actions.operations' => ['tr' => 'İşlemler', 'ru' => 'Операции'],
            'admin.actions.change_status' => ['tr' => 'Durum Değiştir', 'ru' => 'Изменить статус'],
            'admin.actions.actions' => ['tr' => 'İşlemler', 'ru' => 'Действия'],
            'admin.actions.unblock_activate' => ['tr' => 'Engeli Kaldır / Aktifleştir', 'ru' => 'Разблокировать / Активировать'],
            'admin.actions.block_disable' => ['tr' => 'Engelle / Devre Dışı Bırak', 'ru' => 'Заблокировать / Отключить'],
            'admin.actions.verify_email' => ['tr' => 'E-postayı Doğrula', 'ru' => 'Верифицировать email'],
            'admin.actions.credit_debit' => ['tr' => 'Kredi/Borç', 'ru' => 'Кредит/Дебет'],
            'admin.actions.edit_user' => ['tr' => 'Kullanıcıyı Düzenle', 'ru' => 'Редактировать пользователя'],
            'admin.actions.manual_trade' => ['tr' => 'Manuel İşlem', 'ru' => 'Ручная сделка'],
            'admin.actions.create_signal' => ['tr' => 'Sinyal Oluştur', 'ru' => 'Создать сигнал'],
            'admin.actions.send_notification' => ['tr' => 'Bildirim Gönder', 'ru' => 'Отправить уведомление'],
            'admin.actions.user_tax' => ['tr' => 'Kullanıcı Vergisi', 'ru' => 'Налог пользователя'],
            'admin.actions.withdrawal_code' => ['tr' => 'Çekim Kodu', 'ru' => 'Код вывода'],
            'admin.actions.set_trade_count' => ['tr' => 'İşlem Sayısını Ayarla', 'ru' => 'Установить количество сделок'],
            'admin.actions.switch_to_user' => ['tr' => 'Kullanıcıya Geç', 'ru' => 'Переключиться на пользователя'],
            'admin.actions.clear_account' => ['tr' => 'Hesabı Temizle', 'ru' => 'Очистить аккаунт'],
            'admin.actions.delete_account' => ['tr' => 'Hesabı Sil', 'ru' => 'Удалить аккаунт'],
            'admin.actions.view_transactions' => ['tr' => 'İşlemleri Görüntüle', 'ru' => 'Просмотреть транзакции'],
            'admin.actions.add_new_note' => ['tr' => 'Yeni Not Ekle', 'ru' => 'Добавить новую заметку'],
            'admin.actions.edit_note' => ['tr' => 'Notu Düzenle', 'ru' => 'Редактировать заметку'],
            'admin.actions.delete_note' => ['tr' => 'Notu Sil', 'ru' => 'Удалить заметку'],
            'admin.actions.add_first_note' => ['tr' => 'İlk Notu Ekle', 'ru' => 'Добавить первую заметку'],
            'admin.actions.save_note' => ['tr' => 'Notu Kaydet', 'ru' => 'Сохранить заметку'],
            'admin.actions.save_changes' => ['tr' => 'Değişiklikleri Kaydet', 'ru' => 'Сохранить изменения'],
            'admin.actions.updating' => ['tr' => 'Güncelleniyor', 'ru' => 'Обновление'],
            'admin.actions.saving' => ['tr' => 'Kaydediliyor', 'ru' => 'Сохранение'],
            'admin.actions.call' => ['tr' => 'Ara', 'ru' => 'Позвонить'],
            'admin.actions.mark_as_profit' => ['tr' => 'Kar Olarak İşaretle', 'ru' => 'Отметить как прибыль'],
            'admin.actions.mark_as_loss' => ['tr' => 'Zarar Olarak İşaretle', 'ru' => 'Отметить как убыток'],
            'admin.actions.mark_as_expired' => ['tr' => 'Süresi Dolmuş Olarak İşaretle', 'ru' => 'Отметить как истекший'],
            'admin.actions.mark_as_active' => ['tr' => 'Aktif Olarak İşaretle', 'ru' => 'Отметить как активный'],
            'admin.actions.delete_trade' => ['tr' => 'İşlemi Sil', 'ru' => 'Удалить сделку'],
            'admin.actions.delete_plan' => ['tr' => 'Planı Sil', 'ru' => 'Удалить план'],
            'admin.actions.save_referral' => ['tr' => 'Referalı Kaydet', 'ru' => 'Сохранить реферала'],
            'admin.actions.password_reset' => ['tr' => 'Şifre Sıfırlama', 'ru' => 'Сброс пароля'],
            'admin.actions.password_reset_warning' => ['tr' => 'Bu işlem kullanıcının şifresini değiştirecektir', 'ru' => 'Это действие изменит пароль пользователя'],
            'admin.actions.yes_reset' => ['tr' => 'Evet, Sıfırla', 'ru' => 'Да, сбросить'],
            'admin.actions.delete_admin' => ['tr' => 'Admin Sil', 'ru' => 'Удалить администратора'],
            'admin.actions.send' => ['tr' => 'Gönder', 'ru' => 'Отправить'],
            'admin.actions.selected' => ['tr' => 'seçili', 'ru' => 'выбрано'],
            'admin.actions.block_short' => ['tr' => 'Engelle', 'ru' => 'Блок'],
            'admin.actions.assign_admin' => ['tr' => 'Admin Ata', 'ru' => 'Назначить администратора'],

            // admin.status - Eksik Durum Terimleri
            'admin.status.unknown' => ['tr' => 'Bilinmeyen', 'ru' => 'Неизвестный'],
            'admin.status.new' => ['tr' => 'Yeni', 'ru' => 'Новый'],
            'admin.status.contacted' => ['tr' => 'İletişime Geçildi', 'ru' => 'Связались'],
            'admin.status.qualified' => ['tr' => 'Nitelikli', 'ru' => 'Квалифицированный'],
            'admin.status.converted' => ['tr' => 'Dönüştürüldü', 'ru' => 'Конвертирован'],
            'admin.status.lost' => ['tr' => 'Kayıp', 'ru' => 'Потерян'],

            // admin.notifications - Eksik Bildirim Mesajları
            'admin.notifications.attention' => ['tr' => 'Dikkat', 'ru' => 'Внимание'],
            'admin.notifications.irreversible_action' => ['tr' => 'Bu işlem geri alınamaz', 'ru' => 'Это действие необратимо'],
            'admin.notifications.error_loading_note' => ['tr' => 'Not yüklenirken hata oluştu', 'ru' => 'Ошибка при загрузке заметки'],
            'admin.notifications.note_deleted_successfully' => ['tr' => 'Not başarıyla silindi', 'ru' => 'Заметка успешно удалена'],
            'admin.notifications.error_deleting_note' => ['tr' => 'Not silinirken hata oluştu', 'ru' => 'Ошибка при удалении заметки'],
            'admin.notifications.note_added_successfully' => ['tr' => 'Not başarıyla eklendi', 'ru' => 'Заметка успешно добавлена'],
            'admin.notifications.error_adding_note' => ['tr' => 'Not eklenirken hata oluştu', 'ru' => 'Ошибка при добавлении заметки'],
            'admin.notifications.note_updated_successfully' => ['tr' => 'Not başarıyla güncellendi', 'ru' => 'Заметка успешно обновлена'],
            'admin.notifications.error_updating_note' => ['tr' => 'Not güncellenirken hata oluştu', 'ru' => 'Ошибка при обновлении заметки'],
            'admin.notifications.phone_number_not_found' => ['tr' => 'Telefon numarası bulunamadı', 'ru' => 'Номер телефона не найден'],
            'admin.notifications.admin_assigned_successfully' => ['tr' => 'Admin başarıyla atandı', 'ru' => 'Администратор успешно назначен'],
            'admin.notifications.error_assigning_admin' => ['tr' => 'Admin atanırken hata oluştu', 'ru' => 'Ошибка при назначении администратора'],
            'admin.notifications.lead_status_updated_successfully' => ['tr' => 'Lead durumu başarıyla güncellendi', 'ru' => 'Статус лида успешно обновлен'],
            'admin.notifications.error_updating_lead_status' => ['tr' => 'Lead durumu güncellenirken hata oluştu', 'ru' => 'Ошибка при обновлении статуса лида'],
            'admin.notifications.admin_assignment_warning' => ['tr' => 'Bu kullanıcıların admin ataması değiştirilecektir', 'ru' => 'Назначение администратора этих пользователей будет изменено'],
            'admin.notifications.status_change_warning' => ['tr' => 'Bu kullanıcıların lead durumu değiştirilecektir', 'ru' => 'Статус лида этих пользователей будет изменен'],

            // admin.filters - Eksik Filter Terimleri
            'admin.filters.search_users' => ['tr' => 'Kullanıcılarda Ara', 'ru' => 'Поиск пользователей'],
            'admin.filters.all_roles' => ['tr' => 'Tüm Roller', 'ru' => 'Все роли'],
            'admin.filters.filter_users_by_status_admin_date' => ['tr' => 'Kullanıcıları duruma, admin\'e ve tarihe göre filtrele', 'ru' => 'Фильтровать пользователей по статусу, администратору и дате'],
            'admin.filters.search_by_name_email_phone' => ['tr' => 'İsim, e-posta veya telefona göre ara', 'ru' => 'Поиск по имени, email или телефону'],

            // admin.pagination - Eksik Pagination Terimleri
            'admin.pagination.total' => ['tr' => 'Toplam', 'ru' => 'Всего'],
            'admin.pagination.records' => ['tr' => 'kayıt', 'ru' => 'записей'],
            'admin.pagination.showing_all_unfiltered' => ['tr' => 'kayıt gösteriliyor (filtresiz)', 'ru' => 'записей показано (без фильтра)'],
            'admin.pagination.records_showing' => ['tr' => 'kayıt gösteriliyor', 'ru' => 'записей показано'],

            // admin.validation - Eksik Validation Mesajları
            'admin.validation.note_title_required' => ['tr' => 'Not başlığı gereklidir', 'ru' => 'Заголовок заметки обязателен'],
            'admin.validation.note_title_min_length' => ['tr' => 'Not başlığı en az 3 karakter olmalıdır', 'ru' => 'Заголовок заметки должен содержать не менее 3 символов'],
            'admin.validation.note_title_max_length' => ['tr' => 'Not başlığı en fazla 100 karakter olabilir', 'ru' => 'Заголовок заметки может содержать не более 100 символов'],
            'admin.validation.note_content_required' => ['tr' => 'Not içeriği gereklidir', 'ru' => 'Содержание заметки обязательно'],
            'admin.validation.note_content_min_length' => ['tr' => 'Not içeriği en az 10 karakter olmalıdır', 'ru' => 'Содержание заметки должно содержать не менее 10 символов'],
            'admin.validation.note_content_max_length' => ['tr' => 'Not içeriği en fazla 1000 karakter olabilir', 'ru' => 'Содержание заметки может содержать не более 1000 символов'],
            'admin.validation.reminder_date_future' => ['tr' => 'Hatırlatma tarihi gelecekte olmalıdır', 'ru' => 'Дата напоминания должна быть в будущем'],
            'admin.validation.please_fix_errors' => ['tr' => 'Lütfen hataları düzeltin', 'ru' => 'Пожалуйста, исправьте ошибки'],
            'admin.validation.password_min_8' => ['tr' => 'Şifre en az 8 karakter olmalı', 'ru' => 'Пароль должен содержать не менее 8 символов'],
            'admin.validation.password_complexity' => ['tr' => 'Büyük harf, küçük harf, sayı içermeli', 'ru' => 'Должен содержать заглавные буквы, строчные буквы, цифры'],

            // admin.security - Eksik Güvenlik Terimleri  
            'admin.security.keep_admin_info_secure' => ['tr' => 'Admin bilgilerini güvenli tutun', 'ru' => 'Держите информацию администратора в безопасности'],

            // admin.modals - Eksik Modal Terimleri
            'admin.modals.confirm_delete_note' => ['tr' => 'Bu notu silmek istediğinizden emin misiniz?', 'ru' => 'Вы уверены, что хотите удалить эту заметку?'],
            'admin.modals.confirm_assign_admin' => ['tr' => 'Bu admin atamasını yapmak istediğinizden emin misiniz?', 'ru' => 'Вы уверены, что хотите назначить этого администратора?'],
            'admin.modals.confirm_update_lead_status' => ['tr' => 'Lead durumunu güncellemek istediğinizden emin misiniz?', 'ru' => 'Вы уверены, что хотите обновить статус лида?'],

            // admin.messages - Yeni Mesaj Kategorisi
            'admin.messages.whatsapp_default_message' => ['tr' => 'Merhaba, Monexa Finance ekibinden size ulaşıyorum.', 'ru' => 'Здравствуйте, я обращаюсь к вам из команды Monexa Finance.'],

            // admin.dashboard - Dashboard Terimleri
            'admin.dashboard.welcome' => ['tr' => 'Hoş Geldiniz', 'ru' => 'Добро пожаловать'],
            'admin.dashboard.active' => ['tr' => 'Aktif', 'ru' => 'Активный'],
            'admin.dashboard.total_deposits' => ['tr' => 'Toplam Para Yatırma', 'ru' => 'Всего депозитов'],
            'admin.dashboard.all_time_total' => ['tr' => 'Tüm Zamanların Toplamı', 'ru' => 'Общий итог за все время'],
            'admin.dashboard.pending' => ['tr' => 'Beklemede', 'ru' => 'В ожидании'],
            'admin.dashboard.pending_deposits' => ['tr' => 'Bekleyen Para Yatırma', 'ru' => 'Ожидающие депозиты'],
            'admin.dashboard.awaiting_approval' => ['tr' => 'Onay Bekliyor', 'ru' => 'Ожидает одобрения'],
            'admin.dashboard.completed' => ['tr' => 'Tamamlandı', 'ru' => 'Завершен'],
            'admin.dashboard.total_withdrawals' => ['tr' => 'Toplam Para Çekme', 'ru' => 'Всего выводов'],
            'admin.dashboard.completed_transactions' => ['tr' => 'Tamamlanan İşlemler', 'ru' => 'Завершенные транзакции'],
            'admin.dashboard.processing' => ['tr' => 'İşleniyor', 'ru' => 'Обработка'],
            'admin.dashboard.pending_withdrawals' => ['tr' => 'Bekleyen Para Çekme', 'ru' => 'Ожидающие выводы'],
            'admin.dashboard.under_review' => ['tr' => 'İnceleme Altında', 'ru' => 'На рассмотрении'],
            'admin.dashboard.total' => ['tr' => 'Toplam', 'ru' => 'Всего'],
            'admin.dashboard.total_users' => ['tr' => 'Toplam Kullanıcı', 'ru' => 'Всего пользователей'],
            'admin.dashboard.all_registered_users' => ['tr' => 'Tüm kayıtlı kullanıcılar', 'ru' => 'Все зарегистрированные пользователи'],
            'admin.dashboard.online' => ['tr' => 'Çevrimiçi', 'ru' => 'Онлайн'],
            'admin.dashboard.active_users' => ['tr' => 'Aktif Kullanıcılar', 'ru' => 'Активные пользователи'],
            'admin.dashboard.currently_active' => ['tr' => 'Şu anda aktif', 'ru' => 'В настоящее время активны'],
            'admin.dashboard.blocked' => ['tr' => 'Engellenen', 'ru' => 'Заблокирован'],
            'admin.dashboard.blocked_users' => ['tr' => 'Engellenen Kullanıcılar', 'ru' => 'Заблокированные пользователи'],
            'admin.dashboard.suspended' => ['tr' => 'Askıya alınmış', 'ru' => 'Приостановлен'],
            'admin.dashboard.plans' => ['tr' => 'Planlar', 'ru' => 'Планы'],
            'admin.dashboard.investment_plans' => ['tr' => 'Yatırım Planları', 'ru' => 'Инвестиционные планы'],
            'admin.dashboard.active_plan' => ['tr' => 'aktif plan', 'ru' => 'активных планов'],
            'admin.dashboard.advanced_system_analytics' => ['tr' => 'Gelişmiş Sistem Analitiği', 'ru' => 'Расширенная аналитика системы'],
            'admin.dashboard.comprehensive_financial_analysis' => ['tr' => 'Kapsamlı finansal analiz ve sistem performansı', 'ru' => 'Комплексный финансовый анализ и производительность системы'],
            'admin.dashboard.this_month' => ['tr' => 'Bu Ay', 'ru' => 'Этот месяц'],
            'admin.dashboard.this_week' => ['tr' => 'Bu Hafta', 'ru' => 'Эта неделя'],
            'admin.dashboard.this_year' => ['tr' => 'Bu Yıl', 'ru' => 'Этот год'],
            'admin.dashboard.total_transactions' => ['tr' => 'Toplam İşlemler', 'ru' => 'Всего транзакций'],

            // admin.common - Ortak Terimler
            'admin.common.admin_panel' => ['tr' => 'Yönetici Paneli', 'ru' => 'Панель администратора'],

            // admin.navigation - Navigasyon Terimleri
            'admin.navigation.deposits' => ['tr' => 'Para Yatırma', 'ru' => 'Депозиты'],
            'admin.navigation.withdrawals' => ['tr' => 'Para Çekme', 'ru' => 'Выводы'],
            'admin.navigation.users' => ['tr' => 'Kullanıcılar', 'ru' => 'Пользователи'],

            // admin.import - Import Sistem Terimleri (Büyük kategori)
            'admin.import.back_to_user_management' => ['tr' => 'Kullanıcı Yönetimine Dön', 'ru' => 'Вернуться к управлению пользователями'],
            'admin.import.title' => ['tr' => 'Kullanıcı İçe Aktarma Sistemi', 'ru' => 'Система импорта пользователей'],
            'admin.import.description' => ['tr' => 'Excel veya CSV dosyalarından toplu kullanıcı aktarımı yapın', 'ru' => 'Выполните массовый импорт пользователей из файлов Excel или CSV'],
            'admin.import.advanced_import' => ['tr' => 'Gelişmiş İçe Aktarma', 'ru' => 'Расширенный импорт'],
            'admin.import.step_file_selection' => ['tr' => 'Dosya Seçimi', 'ru' => 'Выбор файла'],
            'admin.import.step_column_mapping' => ['tr' => 'Sütun Eşleme', 'ru' => 'Сопоставление столбцов'],
            'admin.import.step_import' => ['tr' => 'İçe Aktarma', 'ru' => 'Импорт'],
            'admin.import.step1_title' => ['tr' => 'Dosya Yükleyin', 'ru' => 'Загрузите файл'],
            'admin.import.step1_description' => ['tr' => 'İçe aktarmak istediğiniz kullanıcı verilerini içeren dosyayı seçin', 'ru' => 'Выберите файл с данными пользователей для импорта'],
            'admin.import.drag_drop_here' => ['tr' => 'Dosyanızı buraya sürükleyip bırakın', 'ru' => 'Перетащите файл сюда'],
            'admin.import.or_click_to_select' => ['tr' => 'veya seçmek için tıklayın', 'ru' => 'или нажмите для выбора'],
            'admin.import.select_file' => ['tr' => 'Dosya Seç', 'ru' => 'Выбрать файл'],
            'admin.import.supported_formats' => ['tr' => 'Desteklenen Formatlar', 'ru' => 'Поддерживаемые форматы'],
            'admin.import.excel_format' => ['tr' => 'Excel Formatları', 'ru' => 'Форматы Excel'],
            'admin.import.excel_extensions' => ['tr' => '.xlsx, .xls uzantılı dosyalar', 'ru' => 'файлы с расширением .xlsx, .xls'],
            'admin.import.csv_format' => ['tr' => 'CSV Format', 'ru' => 'Формат CSV'],
            'admin.import.csv_encoding' => ['tr' => 'UTF-8 kodlamalı CSV dosyaları', 'ru' => 'CSV файлы в кодировке UTF-8'],
            'admin.import.max_file_size' => ['tr' => 'Maksimum Dosya Boyutu', 'ru' => 'Максимальный размер файла'],
            'admin.import.file_size_limit' => ['tr' => '10 MB\'ye kadar', 'ru' => 'до 10 МБ'],
            'admin.import.max_rows' => ['tr' => 'Maksimum Satır', 'ru' => 'Максимальное количество строк'],
            'admin.import.row_limit' => ['tr' => '10.000 kullanıcıya kadar', 'ru' => 'до 10 000 пользователей'],
            'admin.import.download_template' => ['tr' => 'Şablon İndir', 'ru' => 'Скачать шаблон'],
            'admin.import.template_description' => ['tr' => 'Doğru format için örnek şablon dosyasını indirin', 'ru' => 'Скачайте пример шаблона файла для правильного формата'],
            'admin.import.download_template_button' => ['tr' => 'Excel Şablonunu İndir', 'ru' => 'Скачать шаблон Excel'],
            'admin.import.continue_column_mapping' => ['tr' => 'Sütun Eşlemeye Devam Et', 'ru' => 'Продолжить сопоставление столбцов'],
            'admin.import.step2_title' => ['tr' => 'Sütunları Eşleştirin', 'ru' => 'Сопоставьте столбцы'],
            'admin.import.step2_description' => ['tr' => 'Excel sütunlarını sistem alanlarıyla eşleştirin', 'ru' => 'Сопоставьте столбцы Excel с полями системы'],
            'admin.import.file_preview' => ['tr' => 'Dosya Önizlemesi', 'ru' => 'Предпросмотр файла'],
            'admin.import.column_mapping_title' => ['tr' => 'Sütun Eşleme', 'ru' => 'Сопоставление столбцов'],
            'admin.import.excel_columns' => ['tr' => 'Excel Sütunları', 'ru' => 'Столбцы Excel'],
            'admin.import.system_fields' => ['tr' => 'Sistem Alanları', 'ru' => 'Поля системы'],
            'admin.import.field_full_name' => ['tr' => 'Ad Soyad', 'ru' => 'Полное имя'],
            'admin.import.required' => ['tr' => 'Gerekli', 'ru' => 'Обязательно'],
            'admin.import.field_full_name_desc' => ['tr' => 'Kullanıcının tam adı', 'ru' => 'Полное имя пользователя'],
            'admin.import.field_email' => ['tr' => 'E-posta', 'ru' => 'Email'],
            'admin.import.field_email_desc' => ['tr' => 'Benzersiz e-posta adresi', 'ru' => 'Уникальный адрес электронной почты'],
            'admin.import.field_phone' => ['tr' => 'Telefon', 'ru' => 'Телефон'],
            'admin.import.optional' => ['tr' => 'İsteğe Bağlı', 'ru' => 'Необязательно'],
            'admin.import.field_phone_desc' => ['tr' => 'Telefon numarası', 'ru' => 'Номер телефона'],
            'admin.import.field_country' => ['tr' => 'Ülke', 'ru' => 'Страна'],
            'admin.import.field_country_desc' => ['tr' => 'Ülke kodu veya adı', 'ru' => 'Код страны или название'],
            'admin.import.field_username' => ['tr' => 'Kullanıcı Adı', 'ru' => 'Имя пользователя'],
            'admin.import.field_username_desc' => ['tr' => 'Sistem kullanıcı adı', 'ru' => 'Системное имя пользователя'],
            'admin.import.field_estimated_value' => ['tr' => 'Tahmini Değer', 'ru' => 'Оценочная стоимость'],
            'admin.import.field_estimated_value_desc' => ['tr' => 'Lead\'in tahmini değeri', 'ru' => 'Оценочная стоимость лида'],
            'admin.import.field_utm_source' => ['tr' => 'UTM Kaynak', 'ru' => 'UTM источник'],
            'admin.import.field_utm_source_desc' => ['tr' => 'Trafik kaynağı', 'ru' => 'Источник трафика'],
            'admin.import.enter_manually_optional' => ['tr' => 'Manuel girin (isteğe bağlı)', 'ru' => 'Введите вручную (необязательно)'],
            'admin.import.field_utm_campaign' => ['tr' => 'UTM Kampanya', 'ru' => 'UTM кампания'],
            'admin.import.field_utm_campaign_desc' => ['tr' => 'Kampanya adı', 'ru' => 'Название кампании'],
            'admin.import.field_first_name' => ['tr' => 'Ad', 'ru' => 'Имя'],
            'admin.import.will_be_merged' => ['tr' => 'Birleştirilecek', 'ru' => 'Будет объединено'],
            'admin.import.field_first_name_desc' => ['tr' => 'Ad Soyad ile birleştirilecek', 'ru' => 'Будет объединено с полным именем'],
            'admin.import.field_last_name' => ['tr' => 'Soyad', 'ru' => 'Фамилия'],
            'admin.import.field_last_name_desc' => ['tr' => 'Ad Soyad ile birleştirilecek', 'ru' => 'Будет объединено с полным именем'],
            'admin.import.mapping_summary' => ['tr' => 'Eşleme Özeti', 'ru' => 'Сводка сопоставления'],
            'admin.import.no_mapping_done' => ['tr' => 'Henüz eşleme yapılmadı', 'ru' => 'Сопоставление еще не выполнено'],
            'admin.import.back_file_selection' => ['tr' => 'Dosya Seçimine Dön', 'ru' => 'Вернуться к выбору файла'],
            'admin.import.continue_import' => ['tr' => 'İçe Aktarmaya Devam Et', 'ru' => 'Продолжить импорт'],
            'admin.import.step3_title' => ['tr' => 'İçe Aktarımı Başlat', 'ru' => 'Начать импорт'],
            'admin.import.step3_description' => ['tr' => 'Ayarları gözden geçirin ve içe aktarımı başlatın', 'ru' => 'Просмотрите настройки и начните импорт'],
            'admin.import.import_settings' => ['tr' => 'İçe Aktarma Ayarları', 'ru' => 'Настройки импорта'],
            'admin.import.skip_duplicate_emails' => ['tr' => 'Duplicate E-postaları Atla', 'ru' => 'Пропустить дублирующиеся email'],
            'admin.import.skip_duplicate_emails_desc' => ['tr' => 'Aynı e-posta adresine sahip kayıtları atla', 'ru' => 'Пропустить записи с одинаковыми адресами email'],
            'admin.import.send_welcome_email' => ['tr' => 'Hoş Geldin E-postası Gönder', 'ru' => 'Отправить приветственный email'],
            'admin.import.send_welcome_email_desc' => ['tr' => 'Yeni kullanıcılara hoş geldin e-postası gönder', 'ru' => 'Отправить приветственный email новым пользователям'],
            'admin.import.default_lead_status' => ['tr' => 'Varsayılan Lead Durumu', 'ru' => 'Статус лида по умолчанию'],
            'admin.import.batch_size' => ['tr' => 'Batch Boyutu', 'ru' => 'Размер пакета'],
            'admin.import.records_50' => ['tr' => '50 kayıt', 'ru' => '50 записей'],
            'admin.import.records_100' => ['tr' => '100 kayıt', 'ru' => '100 записей'],
            'admin.import.records_250' => ['tr' => '250 kayıt', 'ru' => '250 записей'],
            'admin.import.records_500' => ['tr' => '500 kayıt', 'ru' => '500 записей'],
            'admin.import.import_summary_title' => ['tr' => 'İçe Aktarma Özeti', 'ru' => 'Сводка импорта'],
            'admin.import.import_progress_title' => ['tr' => 'İçe Aktarma İlerlemesi', 'ru' => 'Прогресс импорта'],
            'admin.import.progress' => ['tr' => 'İlerleme', 'ru' => 'Прогресс'],
            'admin.import.processed' => ['tr' => 'İşlenen', 'ru' => 'Обработано'],
            'admin.import.successful' => ['tr' => 'Başarılı', 'ru' => 'Успешно'],
            'admin.import.errors' => ['tr' => 'Hata', 'ru' => 'Ошибки'],
            'admin.import.import_results_title' => ['tr' => 'İçe Aktarma Sonuçları', 'ru' => 'Результаты импорта'],
            'admin.import.back_column_mapping' => ['tr' => 'Sütun Eşlemeye Dön', 'ru' => 'Вернуться к сопоставлению столбцов'],
            'admin.import.start_import' => ['tr' => 'İçe Aktarmayı Başlat', 'ru' => 'Начать импорт'],
            'admin.import.complete' => ['tr' => 'Tamamla', 'ru' => 'Завершить'],
            'admin.import.unsupported_format_error' => ['tr' => 'Desteklenmeyen dosya formatı', 'ru' => 'Неподдерживаемый формат файла'],
            'admin.import.file_size_error' => ['tr' => 'Dosya boyutu çok büyük', 'ru' => 'Размер файла слишком большой'],
            'admin.import.file_uploaded_success' => ['tr' => 'Dosya başarıyla yüklendi', 'ru' => 'Файл успешно загружен'],
            'admin.import.empty_file_error' => ['tr' => 'Dosya boş', 'ru' => 'Файл пуст'],
            'admin.import.excel_parse_error' => ['tr' => 'Excel dosyası parse edilemedi', 'ru' => 'Не удалось разобрать файл Excel'],
            'admin.import.no_data' => ['tr' => 'Veri yok', 'ru' => 'Нет данных'],
            'admin.import.header_detection_question' => ['tr' => 'İlk satır başlık içeriyor mu?', 'ru' => 'Содержит ли первая строка заголовки?'],
            'admin.import.first_row' => ['tr' => 'İlk satır', 'ru' => 'Первая строка'],
            'admin.import.second_row' => ['tr' => 'İkinci satır', 'ru' => 'Вторая строка'],
            'admin.import.ok_header' => ['tr' => 'Tamam = Başlık', 'ru' => 'OK = Заголовок'],
            'admin.import.cancel_data' => ['tr' => 'İptal = Veri', 'ru' => 'Отмена = Данные'],
            'admin.import.column' => ['tr' => 'Sütun', 'ru' => 'Столбец'],
            'admin.import.sample' => ['tr' => 'Örnek', 'ru' => 'Пример'],
            'admin.import.mapped' => ['tr' => 'Eşlendi', 'ru' => 'Сопоставлено'],
            'admin.import.name_fields_will_be_merged' => ['tr' => 'Ad ve soyad alanları birleştirilerek ad soyad oluşturulacak', 'ru' => 'Поля имени и фамилии будут объединены для создания полного имени'],
            'admin.import.required_fields_mapped' => ['tr' => 'Gerekli alanlar eşlendi', 'ru' => 'Обязательные поля сопоставлены'],
            'admin.import.missing_required_fields' => ['tr' => 'Eksik gerekli alanlar', 'ru' => 'Отсутствующие обязательные поля'],
            'admin.import.name_field_required' => ['tr' => 'Ad alanı gerekli', 'ru' => 'Поле имени обязательно'],
            'admin.import.total_records' => ['tr' => 'Toplam Kayıt', 'ru' => 'Всего записей'],
            'admin.import.mapped_fields' => ['tr' => 'Eşlenen Alanlar', 'ru' => 'Сопоставленные поля'],
            'admin.import.ready' => ['tr' => 'Hazır', 'ru' => 'Готово'],
            'admin.import.missing' => ['tr' => 'Eksik', 'ru' => 'Отсутствует'],
            'admin.import.status' => ['tr' => 'Durum', 'ru' => 'Статус'],
            'admin.import.manual_utm_values' => ['tr' => 'Manuel UTM Değerleri', 'ru' => 'Ручные UTM значения'],
            'admin.import.values_applied_to_all' => ['tr' => 'Bu değerler tüm kayıtlara uygulanacak', 'ru' => 'Эти значения будут применены ко всем записям'],
            'admin.import.upload_file_first' => ['tr' => 'Önce dosya yükleyin', 'ru' => 'Сначала загрузите файл'],
            'admin.import.email_field_required' => ['tr' => 'E-posta alanı gerekli', 'ru' => 'Поле email обязательно'],
            'admin.import.name_fields_required' => ['tr' => 'Ad alanları gerekli', 'ru' => 'Поля имени обязательны'],
            'admin.import.import_error' => ['tr' => 'İçe aktarma hatası', 'ru' => 'Ошибка импорта'],
            'admin.import.import_process_error' => ['tr' => 'İçe aktarma işleminde hata oluştu', 'ru' => 'Произошла ошибка в процессе импорта'],
            'admin.import.users_imported_successfully' => ['tr' => 'kullanıcı başarıyla içe aktarıldı', 'ru' => 'пользователей успешно импортировано'],
            'admin.import.users_saved_with_passwords' => ['tr' => 'Kullanıcılar otomatik şifrelerle kaydedildi', 'ru' => 'Пользователи сохранены с автоматическими паролями'],
            'admin.import.duplicate_users_detected' => ['tr' => 'duplicate kullanıcı tespit edildi', 'ru' => 'обнаружено дублирующихся пользователей'],
            'admin.import.duplicate_records_skipped' => ['tr' => 'Bu kayıtlar atlandı', 'ru' => 'Эти записи были пропущены'],
            'admin.import.row' => ['tr' => 'Satır', 'ru' => 'Строка'],
            'admin.import.download_duplicate_excel' => ['tr' => 'Duplicate Excel İndir', 'ru' => 'Скачать Excel с дубликатами'],
            'admin.import.records_skipped' => ['tr' => 'kayıt atlandı', 'ru' => 'записей пропущено'],
            'admin.import.records_skipped_reason' => ['tr' => 'Çeşitli nedenlerle atlandı', 'ru' => 'Пропущено по различным причинам'],
            'admin.import.records_with_errors' => ['tr' => 'kayıtta hata', 'ru' => 'записей с ошибками'],
        ];

        foreach ($phrases as $key => $translations) {
            // Ana category ve subcategory'yi ayırt et
            $parts = explode('.', $key);
            $category = implode('.', array_slice($parts, 0, 2)); // admin.users, admin.customers, etc.
            
            // Phrase oluştur
            $phrase = Phrase::firstOrCreate([
                'key' => $key,
            ], [
                'group' => $category,
                'description' => "Missing user management phrase: {$key}",
                'is_active' => true,
            ]);

            // Çevirileri ekle
            foreach ($translations as $locale => $translation) {
                // Language ID'yi bul
                $language = \DB::table('languages')->where('code', $locale)->first();
                if (!$language) {
                    continue; // Dil bulunamazsa geç
                }

                PhraseTranslation::updateOrCreate([
                    'phrase_id' => $phrase->id,
                    'language_id' => $language->id,
                ], [
                    'translation' => $translation,
                    'is_reviewed' => true,
                    'needs_update' => false,
                ]);
            }
        }

        $this->command->info('Missing User Management phrases have been seeded successfully!');
        $this->command->info('Total missing phrases added: ' . count($phrases));
        $this->command->info('New categories: admin.agents, admin.messages, admin.dashboard, admin.common, admin.navigation');
        $this->command->info('Extended categories: admin.users, admin.customers, admin.investments, admin.accounts, admin.forms, admin.actions, admin.status, admin.notifications, admin.filters, admin.pagination, admin.validation, admin.security, admin.modals, admin.import');
    }
}