<?php

/**
 * Admin Layout ve Dashboard Phrase'leri
 * Bu script admin layout ve dashboard sayfaları için gerekli phrase'leri database'e ekler
 */

use App\Models\Language;
use App\Models\Phrase;

return [
    // Admin Navigation - Menü öğeleri
    'admin.navigation' => [
        'dashboard' => ['tr' => 'Kontrol Paneli', 'ru' => 'Панель управления'],
        'users' => ['tr' => 'Kullanıcılar', 'ru' => 'Пользователи'],
        'all_users' => ['tr' => 'Tüm Kullanıcılar', 'ru' => 'Все пользователи'],
        'financial_management' => ['tr' => 'Finans Yönetimi', 'ru' => 'Финансовое управление'],
        'deposits' => ['tr' => 'Yatırımlar', 'ru' => 'Депозиты'],
        'manage_deposits' => ['tr' => 'Yatırımları Yönet', 'ru' => 'Управление депозитами'],
        'withdrawals' => ['tr' => 'Çekimler', 'ru' => 'Выводы'],
        'manage_withdrawals' => ['tr' => 'Çekimleri Yönet', 'ru' => 'Управление выводами'],
        'business_management' => ['tr' => 'İş Yönetimi', 'ru' => 'Управление бизнесом'],
        'email_services' => ['tr' => 'E-posta Servisleri', 'ru' => 'Почтовые сервисы'],
        'kyc_applications' => ['tr' => 'KYC Başvuruları', 'ru' => 'Заявки KYC'],
        'trade_management' => ['tr' => 'İşlem Yönetimi', 'ru' => 'Управление сделками'],
        'content_management' => ['tr' => 'İçerik Yönetimi', 'ru' => 'Управление контентом'],
        'language_phrases' => ['tr' => 'Dil/Cümleler', 'ru' => 'Язык/Фразы'],
        'status_management' => ['tr' => 'Status Yönetimi', 'ru' => 'Управление статусами'],
        'tasks' => ['tr' => 'Görevler', 'ru' => 'Задачи'],
        'create_task' => ['tr' => 'Görev Oluştur', 'ru' => 'Создать задачу'],
        'manage_tasks' => ['tr' => 'Görevleri Yönet', 'ru' => 'Управление задачами'],
        'view_my_tasks' => ['tr' => 'Görevlerimi Görüntüle', 'ru' => 'Посмотреть мои задачи'],
        'managers' => ['tr' => 'Yöneticiler', 'ru' => 'Менеджеры'],
        'managers_list' => ['tr' => 'Yöneticiler Listesi', 'ru' => 'Список менеджеров'],
        'add_manager' => ['tr' => 'Yönetici Ekle', 'ru' => 'Добавить менеджера'],
        'hierarchy_view' => ['tr' => 'Hiyerarşi Görünümü', 'ru' => 'Иерархический вид'],
        'legacy_system' => ['tr' => 'Eski Sistem', 'ru' => 'Старая система'],
        'old_add_manager' => ['tr' => 'Eski Yönetici Ekle', 'ru' => 'Старый добавить менеджера'],
        'old_managers_modern' => ['tr' => 'Eski Yöneticiler (Modern)', 'ru' => 'Старые менеджеры (современный)'],
        'permissions_roles' => ['tr' => 'Yetkiler & Roller', 'ru' => 'Разрешения и роли'],
        'permissions_matrix' => ['tr' => 'İzinler Matrisi', 'ru' => 'Матрица разрешений'],
        'role_management' => ['tr' => 'Rol Yönetimi', 'ru' => 'Управление ролями'],
        'permission_history' => ['tr' => 'İzin Geçmişi', 'ru' => 'История разрешений'],
        'system_management' => ['tr' => 'Sistem Yönetimi', 'ru' => 'Системное управление'],
        'system_settings' => ['tr' => 'Sistem Ayarları', 'ru' => 'Системные настройки'],
        'other_settings' => ['tr' => 'Diğer Ayarlar', 'ru' => 'Другие настройки'],
        'referral_bonus_settings' => ['tr' => 'Tavsiye/Bonus Ayarları', 'ru' => 'Настройки рефералов/бонусов'],
        'payment_settings' => ['tr' => 'Ödeme Ayarları', 'ru' => 'Настройки платежей'],
        'exchange_settings' => ['tr' => 'Takas Ayarları', 'ru' => 'Настройки обмена'],
        'ip_address' => ['tr' => 'IP Adresi', 'ru' => 'IP адрес'],
    ],

    // Admin Dashboard - Dashboard öğeleri
    'admin.dashboard' => [
        'welcome' => ['tr' => 'Hoş Geldiniz!', 'ru' => 'Добро пожаловать!'],
        'control_panel' => ['tr' => 'Kontrol Paneli', 'ru' => 'Панель управления'],
        'management_panel' => ['tr' => 'Yönetim Paneli', 'ru' => 'Панель управления'],
        'system_analytics' => ['tr' => 'Sistem Analitiği', 'ru' => 'Аналитика системы'],
        'advanced_system_analytics' => ['tr' => 'Gelişmiş Sistem Analitiği', 'ru' => 'Расширенная аналитика системы'],
        'financial_overview' => ['tr' => 'Finansal genel bakış ve işlem analitiği', 'ru' => 'Финансовый обзор и анализ транзакций'],
        'comprehensive_financial_analysis' => ['tr' => 'Kapsamlı finansal performans analizi ve trend görünümü', 'ru' => 'Комплексный анализ финансовых показателей и трендов'],
        'total_deposits' => ['tr' => 'Toplam Yatırımlar', 'ru' => 'Общие депозиты'],
        'pending_deposits' => ['tr' => 'Bekleyen Yatırımlar', 'ru' => 'Ожидающие депозиты'],
        'total_withdrawals' => ['tr' => 'Toplam Çekimler', 'ru' => 'Общие выводы'],
        'pending_withdrawals' => ['tr' => 'Bekleyen Çekimler', 'ru' => 'Ожидающие выводы'],
        'total_users' => ['tr' => 'Toplam Kullanıcılar', 'ru' => 'Общее количество пользователей'],
        'active_users' => ['tr' => 'Aktif Kullanıcılar', 'ru' => 'Активные пользователи'],
        'blocked_users' => ['tr' => 'Engellenen Kullanıcılar', 'ru' => 'Заблокированные пользователи'],
        'investment_plans' => ['tr' => 'Yatırım Planları', 'ru' => 'Инвестиционные планы'],
        'all_time_total' => ['tr' => 'Tüm zamanlar toplamı', 'ru' => 'Общий итог за все время'],
        'awaiting_approval' => ['tr' => 'Onay bekliyor', 'ru' => 'Ожидает одобрения'],
        'completed_transactions' => ['tr' => 'Tamamlanan işlemler', 'ru' => 'Завершенные транзакции'],
        'under_review' => ['tr' => 'İnceleniyor', 'ru' => 'На рассмотрении'],
        'currently_online' => ['tr' => 'Şu anda çevrimiçi', 'ru' => 'В настоящее время онлайн'],
        'suspended_accounts' => ['tr' => 'Askıya alınmış hesaplar', 'ru' => 'Приостановленные аккаунты'],
        'available_plans' => ['tr' => 'Mevcut planlar', 'ru' => 'Доступные планы'],
        'total_registered' => ['tr' => 'Toplam kayıtlı', 'ru' => 'Всего зарегистрировано'],
        'currently_active' => ['tr' => 'Şu anda aktif', 'ru' => 'В настоящее время активно'],
        'registered_users' => ['tr' => 'Kayıtlı tüm kullanıcılar', 'ru' => 'Все зарегистрированные пользователи'],
        'active' => ['tr' => 'Aktif', 'ru' => 'Активный'],
        'waiting' => ['tr' => 'Bekliyor', 'ru' => 'Ожидание'],
        'completed' => ['tr' => 'Tamamlandı', 'ru' => 'Завершено'],
        'processing' => ['tr' => 'İşleniyor', 'ru' => 'Обрабатывается'],
        'total' => ['tr' => 'Toplam', 'ru' => 'Общий'],
        'online' => ['tr' => 'Çevrimiçi', 'ru' => 'Онлайн'],
        'blocked' => ['tr' => 'Engelli', 'ru' => 'Заблокирован'],
        'plans' => ['tr' => 'Planlar', 'ru' => 'Планы'],
        'total_transactions' => ['tr' => 'Toplam İşlemler', 'ru' => 'Общие транзакции'],
    ],

    // Admin Common - Genel admin terimleri  
    'admin.common' => [
        'admin_panel' => ['tr' => 'Admin Panel', 'ru' => 'Админ панель'],
        'loading' => ['tr' => 'Yükleniyor...', 'ru' => 'Загрузка...'],
        'notifications' => ['tr' => 'Bildirimler', 'ru' => 'Уведомления'],
        'new' => ['tr' => 'yeni', 'ru' => 'новый'],
        'account_settings' => ['tr' => 'Hesap Ayarları', 'ru' => 'Настройки аккаунта'],
        'change_password' => ['tr' => 'Şifre Değiştir', 'ru' => 'Изменить пароль'],
        'logout' => ['tr' => 'Çıkış Yap', 'ru' => 'Выйти'],
        'no_notifications' => ['tr' => 'Henüz bildirim yok', 'ru' => 'Уведомлений пока нет'],
        'language_selection' => ['tr' => 'Dil Seçimi', 'ru' => 'Выбор языка'],
        'theme_toggle' => ['tr' => 'Tema Değiştir', 'ru' => 'Переключить тему'],
        'collapse' => ['tr' => 'Daralt', 'ru' => 'Свернуть'],
        'expand' => ['tr' => 'Genişlet', 'ru' => 'Развернуть'],
        'search_users' => ['tr' => 'Kullanıcıları ara...', 'ru' => 'Найти пользователей...'],
        'today' => ['tr' => 'Bugün', 'ru' => 'Сегодня'],
        'this_week' => ['tr' => 'Bu Hafta', 'ru' => 'На этой неделе'],
        'this_month' => ['tr' => 'Bu Ay', 'ru' => 'В этом месяце'],
        'this_year' => ['tr' => 'Bu Yıl', 'ru' => 'В этом году'],
        'copyright' => ['tr' => '© {{ year }}', 'ru' => '© {{ year }}'],
        'more_notifications' => ['tr' => 'adet daha bildirim var', 'ru' => 'еще уведомлений'],
    ],

    // Admin Buttons - Button metinleri
    'admin.buttons' => [
        'mark_all_read' => ['tr' => 'Tümünü Okunmuş İşaretle', 'ru' => 'Отметить все как прочитанное'],
        'view_all' => ['tr' => 'Tümünü Gör', 'ru' => 'Посмотреть все'],
        'save' => ['tr' => 'Kaydet', 'ru' => 'Сохранить'],
        'cancel' => ['tr' => 'İptal', 'ru' => 'Отмена'],
        'edit' => ['tr' => 'Düzenle', 'ru' => 'Редактировать'],
        'delete' => ['tr' => 'Sil', 'ru' => 'Удалить'],
        'create' => ['tr' => 'Oluştur', 'ru' => 'Создать'],
        'update' => ['tr' => 'Güncelle', 'ru' => 'Обновить'],
        'close' => ['tr' => 'Kapat', 'ru' => 'Закрыть'],
        'submit' => ['tr' => 'Gönder', 'ru' => 'Отправить'],
        'reset' => ['tr' => 'Sıfırla', 'ru' => 'Сбросить'],
        'back' => ['tr' => 'Geri', 'ru' => 'Назад'],
    ],

    // Admin Forms - Form öğeleri
    'admin.forms' => [
        'required_field' => ['tr' => 'Bu alan zorunludur', 'ru' => 'Это поле обязательно'],
        'invalid_input' => ['tr' => 'Geçersiz giriş', 'ru' => 'Неверный ввод'],
        'search_placeholder' => ['tr' => 'Aramaya başlayın...', 'ru' => 'Начните поиск...'],
        'select_option' => ['tr' => 'Seçenek seçin', 'ru' => 'Выберите вариант'],
        'no_results' => ['tr' => 'Sonuç bulunamadı', 'ru' => 'Результаты не найдены'],
        'loading_results' => ['tr' => 'Sonuçlar yükleniyor...', 'ru' => 'Загрузка результатов...'],
        'filter_by' => ['tr' => 'Filtrele:', 'ru' => 'Фильтровать по:'],
        'sort_by' => ['tr' => 'Sırala:', 'ru' => 'Сортировать по:'],
        'per_page' => ['tr' => 'Sayfa başına', 'ru' => 'На страницу'],
        'showing_results' => ['tr' => ':total sonuçtan :from - :to arası gösteriliyor', 'ru' => 'Показано :from - :to из :total результатов'],
    ],

    // Admin Notification Types - Bildirim türleri
    'admin.notifications' => [
        'deposit' => ['tr' => 'Yatırım', 'ru' => 'Депозит'],
        'withdrawal' => ['tr' => 'Çekim', 'ru' => 'Вывод'],
        'plan_purchase' => ['tr' => 'Plan Alımı', 'ru' => 'Покупка плана'],
        'bot_purchase' => ['tr' => 'Bot Alımı', 'ru' => 'Покупка бота'],
        'trade' => ['tr' => 'İşlem', 'ru' => 'Сделка'],
        'profit' => ['tr' => 'Kâr', 'ru' => 'Прибыль'],
        'login' => ['tr' => 'Giriş', 'ru' => 'Вход'],
        'notification' => ['tr' => 'Bildirim', 'ru' => 'Уведомление'],
    ],
];